### ISSUE TITLE
Social

### ISSUE THREAD

**Issue by azet12** [FiltersHeroes/PolishAnnoyanceFilters#1]
.

**Comment by blocker999** [comment]
Do którego popupera? wolałbym osobno jako drugi plik albo jako aktualizacje&nbsp;Polskich filtrów elementów społecznościach od&nbsp;MajkiIT, narazie mam zielone światło od niego ale co i jak dokładnie to zobacze, jego paczka jest już jakiś czas a niechciałbym dublować paczek no chyba że ma Pan lepsze rozwiązanie, to proszę o sugestie a dyskusja na ten temat toczy się tu:https://github.com/MajkiIT/polish-ads-filter/issues/1425
