### ISSUE TITLE
shinden.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#1001]
### Typ elementu 
błąd
### Link bezpośredni 
`https://shinden.pl/external-video/51930-boku-no-hero-academia-3rd-season/view/163877`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Slimjet Wersja 19.0.9.0 (oparty o Chromium 66.0.3359.117) (Oficjalna wersja) (32-bitowa)
**Bloker:** uBlock Origin 1.16.14
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
Wykrywa i prosi o wyłączenie adblokad.

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by MajkiIT** [comment]
@hawkeye116477 Do zamknięcia 
https://github.com/MajkiIT/polish-ads-filter/commit/255c7818bbe7f5041236545e2a671950269bfb81#diff-ca815c4f5fe404637a9387f434740d25
