### ISSUE TITLE
pebx.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#1004]
### Typ elementu 
błąd
### Link bezpośredni 
`https://pebx.pl/js/donate.js`
### Moja konfiguracja 
**System operacyjny:** Mac
**Przeglądarka internetowa:** Google Chrome 68.0.3440.106
**Bloker:** uBlock Origin 1.16.16
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
Popularny strona z skryptem do kopania kryptowalut (https://pebx.pl/js/donate.js) kod po obfuskacji

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by hawkeye116477** [comment]
My się nie zajmujemy takimi rzeczami, to do @MajkiIT.

**Comment by MajkiIT** [comment]
https://github.com/MajkiIT/polish-ads-filter/commit/730e29de151f5068e78a808d3c99db909c3f58e0#diff-711027ed0794992ae3b8710d874f3df7
