### ISSUE TITLE
newsbook.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#1020]
### Typ elementu 
prawy klik
### Link bezpośredni 
`http://newsbook.pl`
### Moja konfiguracja 
**System operacyjny:** Linux
**Przeglądarka internetowa:** Google Chrome 71
**Bloker:** uBlock Origin 1.17.0
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane anonimowo przez użytkownika.

Zablokowane jakimś skryptem - niby można odblokować na kilka sposobów ale tekstu nie zaznaczysz.

**Comment by krystian3w** [comment]
### HTML Filtering:

```
newsbook.pl##^#wpcp_disable_Right_Click, #wpcp_disable_selection, #wpcp_css_disable_selection
newsbook.pl##^style:has-text(.unselectable)
```

### CSS / Wstrzykiwanie skryptów:

```
newsbook.pl##script:inject(abort-current-inline-script.js, document.onkeydown)
newsbook.pl##.unselectable, html:style(-webkit-usser-select: text !important; -moz-user-select: text !important; -ms-user-select: text !important; user-select: text !important; cursor: unset !important;)
```

###### Wątpliwość (nie wiem co wydajniejsze / bezpieczniejsze):
```
newsbook.pl##script:inject(abort-current-inline-script.js, nocontext)

! lub

newsbook.pl##script:inject(abort-on-property-write.js, nocontext)
```
---

Na liście odblokowywać zaznaczanie tekstów, <kbd>Ctrl</kbd> + <kbd>V</kbd> / <kbd>C</kbd> / <kbd>X</kbd> / <kbd>A</kbd> / <kbd>U</kbd> / <kbd>P</kbd>? 

Czy sam prawy klik i niech teksty sobie OCR kopiują / komentarze na siłę od zera piszą?

**Comment by hawkeye116477** [comment]
Sam klik.
