### ISSUE TITLE
nbi.com.pl

### ISSUE THREAD

**Issue by xMaap** [FiltersHeroes/PolishAnnoyanceFilters#1039]
![opera zdjecie_2018-11-13_042946_www nbi com pl](https://user-images.githubusercontent.com/36385327/48389236-e00e9800-e6fc-11e8-82ac-98353bd0d9b3.png)

### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [x] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
`##.fancybox-wrap, #fancybox-overlay`

**Comment by hawkeye116477** [comment]
A to nie dla Majka, bo wygląda na reklamę?

**Comment by krystian3w** [comment]
@MajkiIT

**Comment by MajkiIT** [comment]
@krystian3w dziękuje
