### ISSUE TITLE
easyprotect.pl

### ISSUE THREAD

**Issue by xMaap** [FiltersHeroes/PolishAnnoyanceFilters#1045]
Myślę, że jednak ta opcja jest przydatna.

Włączony
![opera zdjecie_2018-11-19_004205_easyprotect pl](https://user-images.githubusercontent.com/36385327/48679729-2ac46000-eb94-11e8-919a-b58cdc358896.png)
Wyłączony
![opera zdjecie_2018-11-19_004241_easyprotect pl](https://user-images.githubusercontent.com/36385327/48679732-2f891400-eb94-11e8-83b3-a664be5a9247.png)

### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [] Wyskakujące okienko (popup)
- [] Inny element
- [x] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
Na to nic nie poradzimy, opisz czy chodzi tylko o zdjęcie ładujące się za drugą wizytą.

Scroll mogę kolejny raz w cookies poprawić jak na Operze nie działa z Nano Adblockerem (był z dwie zmiany w budowie CSS i zakończyło się na połączeniu reguł w jedną gdy te działałaby mi w Vivaldim + Nano Adblocker).

---

Opcjonalnie mogę im zgłosić, że zdjęcie nie ładuje się przy pierwszy odwiedzinach  - może za miesiąc naprawią buga w szablonie.

**Comment by krystian3w** [comment]
Na razie nie odpisali i chyba nie odpiszą, mail "`info`" nie wygląda na taki by ktoś uważał, że trzeba coś odpowiedzieć lub przekazać do odpowiedniego działu.

**Comment by krystian3w** [comment]
Chyba naprawili, już się normalnie ładuje.
