### ISSUE TITLE
morele.net | sklep-presto.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#1052]
### Typ elementu
popup
### Link bezpośredni 
`https://www.morele.net/`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Opera 56
**Bloker:** uBlock Origin 1.17.0
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
Powiązane:

```
amfora.pl
budujesz.pl
digitalo.pl
hulahop.pl
meblujesz.pl
morele.net
motoria.pl
pupilo.pl
sklep-presto.pl
ubieramy.pl
```

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
CSS-em (daje rady nadpisać on `pointer-events`) i html filteringiem (rozwala się ładowanie strony) się nie da.

**Comment by krystian3w** [comment]
CSS-em (nie daje rady nadpisać on `pointer-events`) i html filteringiem (rozwala się ładowanie strony) się nie da.

**Comment by krystian3w** [comment]
```
!#if !cap_user_stylesheet
amfora.pl,budujesz.pl,digitalo.pl,hulahop.pl,meblujesz.pl,morele.net,motoria.pl,pupilo.pl,sklep-presto.pl,ubieramy.pl##.new-page-info-dialog.morele-dialog
amfora.pl,budujesz.pl,digitalo.pl,hulahop.pl,meblujesz.pl,morele.net,motoria.pl,pupilo.pl,sklep-presto.pl,ubieramy.pl##body.morele-dialog-show>:not(.morele-dialog):style(pointer-events: auto;)
!#endif
```

Takie coś działa w Nano Adblocker, wychwyciłem to po użyciu np. Stylus.

Może o takie bugi chodziło :penguin:?

**Comment by krystian3w** [comment]
Koniec emisji
