### ISSUE TITLE
czarymary.pl [2]

### ISSUE THREAD

**Issue by garrgamel** [FiltersHeroes/PolishAnnoyanceFilters#1242]
### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [x] Wyskakujące okienko (popup)
- [] Inny element
- [ ] Błąd
- [] Pytanie
- [] Ulepszenie

Reopen #1177 , na Operze naprawione, ale na Firefoxie dalej to jest.

(Póki co zgłaszam tylko takie elementy, więc jeśli na stronie znajdą się jeszcze jakieś inne elementy do zgłoszenia, to niech inni się nimi zajmują, ja się innymi elementami na razie nie zajmuję.), używam tylko 2 modułów:
- Newslettery (bez wyskakujących okienek)
- Wyskakujące Okienka

więc jeśli czasem zdarzy się, że coś u kogoś się nie pojawia bo ma włączone inne moduły lub całą listę EI to niech spróbuje tylko na tych 2 modułach.

**Comment by hawkeye116477** [comment]
Dziwna sprawa, u mnie to `||czarymary.pl/newsletterpopup ` działa.

**Comment by garrgamel** [comment]
Miałem i mam co trzeba aktualne, dalej na Firefoxie to wyskakuje, pomimo, że w loggerze jest ten filtr:

`||czarymary.pl/newsletterpopup | -- | xhr | https://www.czarymary.pl/NewsletterPopup/Id-26/Ajax-0`

Dopiero gdy włączę moduł: `Polskie Filtry Elementów Irytujących - Powiadomienia Web Push ` to komunikat znika.

**Comment by garrgamel** [comment]
> blocker999 : Umie jest ok na Firefoxie

 na tylko tych 2 modułach ? :
 -  Newslettery (bez wyskakujących okienek)
 -  Wyskakujące Okienka

Raczej moduł `Push` ci to wycina.

Spoko, jak `Push` to `Push`, chyba zacznę korzystać z tego modułu `Push` skoro tyle tych wyskakujących newsletterów pushowych.
