### ISSUE TITLE
zsjedlicze.pl

### ISSUE THREAD

**Issue by gomoku** [FiltersHeroes/PolishAnnoyanceFilters#125]
Sorry za zduplikowanie wątku, właśnie się zorientowałem, że już istnieje tu: https://github.com/azet12/PopupBlocker/issues/21

U góry header przy przewijaniu strony w górę/w dół jeździ za scrollem:
http://www.zsjedlicze.pl/art,139,zobaczylismy-jak-jest-w-areszcie
http://nabor.zsjedlicze.pl/index.php?c=article&id=156
Próbowałem go usadzić tymi filtrami (każdym z osobna oraz obydwoma na raz ale mi nie wychodzi:
```
zsjedlicze.pl###toolbarWrapper:style(position: static!important;)
zsjedlicze.pl###toolbarBg:style(position: static!important;)
```

![](https://s3.dodajfote.pl/2017/09/20/4692fa.png)

**Comment by hawkeye116477** [comment]
@gomoku Można tak to zrobić, ale wtedy nie będzie za ładnie to wyglądać. Innych pomysłów nie mam, a u Adama jesteśmy na 999 miejscu w kolejce 😃 .
```
zsjedlicze.pl###toolbarBg:style(position: absolute!important;)
zsjedlicze.pl###toolbarWrapper:style(position: absolute!important;)
```

**Comment by gomoku** [comment]
@hawkeye116477 to trzeba będzie poczekać, bo zarówno twój filtr jak i mój powodują zbyt dużą demolkę.
