### ISSUE TITLE
pushwhy.com, pushnice.com, pushgaga.com

### ISSUE THREAD

**Issue by MajkiIT** [FiltersHeroes/PolishAnnoyanceFilters#1332]
PUSH

```
||pushwhy.com/$xmlhttprequest
||pushnice.com$script
||pushgaga.com/$script
```

**Comment by hawkeye116477** [comment]
@MajkiIT A gdzie to jest? Bo jeżeli chodzi o `anime-odcinki.pl`, to tam raczej nie pomaga blokowanie tego, a dla uBO jest już reguła na prośby o możliwość wyświetlenia pusha.

**Comment by krystian3w** [comment]
Może propozycja blokowania odgórnie domen, pomijając już `anime-odcinki.pl`.

**Comment by hawkeye116477** [comment]
Na razie póki co, jak nie znaleźliśmy tego nigdzie indziej, to raczej sobie odpuścimy.

**Comment by krystian3w** [comment]
`pushwhy.com` - 92 i brak "polskich"
`pushnice.com` - 39 i brak "polskich"
`pushgaga.com` - 48 i brak "polskich"

**Comment by MajkiIT** [comment]
@krystian3w Co rozumiesz przez to powyżej ?

**Comment by krystian3w** [comment]
Że `nerdydata.com` nic polskiego nie znajduje (8, 6, 0 domen gdzie niby mogą być te pushe i żadna nie wygląda by była spolszczona).

A `publicwww.com`  tyle domen j.w., ale żadna nie "`.pl`" lub maksymalnie 3 są widoczne jak im się nie wpłaci 50$/500$.
