### ISSUE TITLE
kurierlubelski.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#1334]
### Typ elementu
widżet
### Link bezpośredni 
``
### Moja konfiguracja 
**System operacyjny:** Android
**Przeglądarka internetowa:** Mozilla Firefox 51
**Bloker:** uBlock Origin 1.0.3
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by hawkeye116477** [comment]
My się tym nie zajmujemy, to robota dla @olegwukr.
