### ISSUE TITLE
pixers.biz

### ISSUE THREAD

**Issue by poompon** [FiltersHeroes/PolishAnnoyanceFilters#1358]
### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [x] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

popup (newsletter/subskrybcja/zapisz się/polub nas/dołącz do nas itp.)

![ss_082](https://user-images.githubusercontent.com/45519946/51264504-f237db80-19b6-11e9-9c41-5149ed2f57d2.png)

(Póki co zgłaszam tylko takie elementy, więc jeśli na stronie znajdą się jeszcze jakieś inne elementy do zgłoszenia, to niech inni się nimi zajmują, ja się innymi elementami na razie nie zajmuję.), używam tylko 3 modułów:

Newslettery (bez wyskakujących okienek)
Wyskakujące Okienka
Powiadomienia Web Push

więc jeśli czasem zdarzy się, że coś u kogoś się nie pojawia bo ma włączone inne moduły lub całą listę EI to niech spróbuje tylko na tych 3 modułach.

**Comment by krystian3w** [comment]
`||assets.livecall.io/*/widget.js$script,domain=pixers.biz`

i po pop-upie ale jak to dodawać @hawkeye116477  / @blocker999  by nie robić duplikatów i nie zmusić użytkowników do używania aż 3 list (popupy, push, widgety kontaktowe).

**Comment by hawkeye116477** [comment]
Jak to popup, to do popupów.

**Comment by krystian3w** [comment]
Ale bez rewolucji sprawdzającej czy inne kontaktowe też mają atakujący pop-up po jakimś dłuższym siedzeniu na stronie?

**Comment by hawkeye116477** [comment]
@krystian3w Bez

**Comment by krystian3w** [comment]
To znaczy przerobić na kosmetyczne może, że na jednej wytnę button a na drugiej pop-up pojawiający się po kilku minutach?

I bym sprawdził tylko jak jest w wypadku tych z `livecall.io` - `polskimarket.nl`, `debesis.pl`

**Comment by hawkeye116477** [comment]
@krystian3w A popup pojawiający się po naciśnięciu przycisku nie jest ten sam? Zwykle tak raczej chyba było, że wszystko razem wycinaliśmy w popupach. Jak ktoś się będzie chciał skontaktować, to zresztą ma zwykły kontakt.

**Comment by krystian3w** [comment]
Bardziej chodzi mi o modularność, tam można słuchawkę wyciąć i niech się pop-up włącza przy pierwszych odwiedzinach.

**Comment by krystian3w** [comment]
Jeszcze muszę ponownie przebadać jak wycinany jest na #906, kosmetycznie nic go nie łapało, stąd myślałem,  że go nie ma, a po całkowitym wyłączeniu dalej jest.

**Comment by krystian3w** [comment]
#1369

**Comment by krystian3w** [comment]
Niby od 26 lutego zamknęli działalność.
