### ISSUE TITLE
ivel.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#1386]
### Typ elementu
popup
### Moja konfiguracja 
**System operacyjny:** Linux
**Przeglądarka internetowa:** Mozilla Firefox 64.0
**Bloker:** uBlock Origin v1.18.0
**Używane filtry:** 
https://pastebin.com/LbWm83zy
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by d21d3q** [comment]
Jak coś to ja to dodoałem przez stronkę.

**Comment by hawkeye116477** [comment]
@d21d3q Ok, a tak w ogóle, to nie potrzebujesz `https://raw.githubusercontent.com/PolishFiltersTeam/PolishAnnoyanceFilters/master/PAF_pop-ups.txt`, wystarczy tylko PPB.txt, PAF_pop-ups to wyodrębniona sekcja z popupami z PPB.txt, tak jakby ktoś nie lubił tylko pop-upów :smile:.

A tego pop-upa nie widzę. Mógłbym prosić o zrzut ekranu?

**Comment by krystian3w** [comment]
Ale to stara reguła: https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/commit/30e2241e2311ae5a67772953518b764a2fb3c393 

z rok ma pewnie jakby grzebać dalej wstecz.

**Comment by d21d3q** [comment]
tak też mogło być, bo z obecnym zestawem już mi się to nie pokazuje
