### ISSUE TITLE
radioradom.pl

### ISSUE THREAD

**Issue by poompon** [FiltersHeroes/PolishAnnoyanceFilters#1404]
### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [x] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

popup (newsletter/subskrybcja/zapisz się/polub nas/dołącz do nas/nagabywanie itp.)
było zgłaszane tam: https://github.com/MajkiIT/polish-ads-filter/issues/11653 ale nie zostało naprawione, więc zgłaszam tu, no chyba, że to raczej zalicza się reklam wewn.

![ss_082](https://user-images.githubusercontent.com/45519946/51804330-ab23d300-225f-11e9-94f2-b8933ad72080.png)

(Póki co zgłaszam tylko takie elementy, więc jeśli na stronie znajdą się jeszcze jakieś inne elementy do zgłoszenia, to niech inni się nimi zajmują, ja się innymi elementami na razie nie zajmuję.), używam 5 modułów:

- Newslettery (bez wyskakujących okienek)
- Wyskakujące Okienka
- Powiadomienia Web Push
- AdGuard Popups
- AdGuard Push-notifications

więc jeśli czasem zdarzy się, że coś u kogoś się nie pojawia bo ma włączone inne moduły lub całą listę EI to niech spróbuje tylko na tych 5 modułach.

**Comment by hawkeye116477** [comment]
To jest reklama, @MajkiIT zgłoś się.

**Comment by poompon** [comment]
> 
> 
> Już to zgłaszałem wcześniej, pop-upy reklamowe do Majkiego trzeba zgłaszać.
> 
> [MajkiIT/polish-ads-filter#11653](https://github.com/MajkiIT/polish-ads-filter/issues/11653)

Jakbym kur.. nikt wiedział, a ty w ogóle umiesz czytać co napisałem w pierwszym komentarzu https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/1404#issue-403573669:

> poompon: było zgłaszane tam: MajkiIT/polish-ads-filter#11653 ale nie zostało naprawione, więc zgłaszam tu, no chyba, że to raczej zalicza się reklam wewn.

Nie naprawił u siebie, to jego problem, więc zgłosiłem tu, jeśli chcesz to idź i zgłaszaj po 10 razy to samo.

**Comment by poompon** [comment]
Proponuje temu, który bawi się i ukrył mój komentarz, żeby ukrył też komentarz blocker999 'a jako spam bo powtarza (spamuje) to co napisałem wcześniej w pierwszym komentarzu i to co napisał hawkeye116477 w swoim, a ja tylko odpisałem mu na ten jego spam i głupie uwagi więc nie wiem dlaczego, została ukryta tylko moja odpowiedź na ten spam i głupie uwagi, a komentarz z samym spamem i głupimi uwagami nie został ukryty, ale to pewnie ktoś mi po złości robi.

**Comment by hawkeye116477** [comment]
Jak zwykle, zaczyna się awantura wraz z wyzwiskami i doszły jeszcze groźby...
Jakby co, to zapewne to @krystian3w ukrył, ale ja tam bym nie robił z tego takiego wielkiego halo, złość piękności szkodzi :smile:.
