### ISSUE TITLE
szlachetnapaczka.pl

### ISSUE THREAD

**Issue by pomidoor** [FiltersHeroes/PolishAnnoyanceFilters#1496]
### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [] Wyskakujące okienko (popup)
- [x] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

![anim 003](https://user-images.githubusercontent.com/44265754/53366199-4ed9cf00-3943-11e9-8850-8b2d15524077.gif)

![ss_040](https://user-images.githubusercontent.com/44265754/53366227-5dc08180-3943-11e9-8486-b9c4a4c68c7d.png)

(Póki co zgłaszam tylko takie elementy, więc jeśli na stronie znajdą się jeszcze jakieś inne elementy do zgłoszenia, to niech inni się nimi zajmują, ja się innymi elementami na razie nie zajmuję.), używam 6 modułów:

- Newslettery (bez wyskakujących okienek)
- Wyskakujące Okienka
- Powiadomienia Web Push
- Polskie Filtry Elementów Irytujących - Widżety Kontaktowe/Informacji Zwrotnej
- AdGuard Popups
- AdGuard Push-notifications

więc jeśli czasem zdarzy się, że coś u kogoś się nie pojawia bo ma włączone inne moduły lub całą listę EI to niech spróbuje tylko na tych 6 modułach.

**Comment by krystian3w** [comment]
Chyba skończyła się im kampania reklamowa e-pitów :green_apple:  :green_book: :green_heart:  :green_salad: .

**Comment by pomidoor** [comment]
Też już tego nie mam, wygasło.
