### ISSUE TITLE
kwit.pl

### ISSUE THREAD

**Issue by pomidoor** [FiltersHeroes/PolishAnnoyanceFilters#1517]
### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [x] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

popup (newsletter/subskrybcja/zapisz się/polub nas/dołącz do nas/nagabywanie itp.)

![ss_010](https://user-images.githubusercontent.com/44265754/53638957-2e05c800-3c28-11e9-9d4e-17d93d86880b.png)

(Póki co zgłaszam tylko takie elementy, więc jeśli na stronie znajdą się jeszcze jakieś inne elementy do zgłoszenia, to niech inni się nimi zajmują, ja się innymi elementami na razie nie zajmuję.), używam 6 modułów:

- Newslettery (bez wyskakujących okienek)
- Wyskakujące Okienka
- Powiadomienia Web Push
- Polskie Filtry Elementów Irytujących - Widżety Kontaktowe/Informacji Zwrotnej
- AdGuard Popups
- AdGuard Push-notifications

więc jeśli czasem zdarzy się, że coś u kogoś się nie pojawia bo ma włączone inne moduły lub całą listę EI to niech spróbuje tylko na tych 6 modułach.

**Comment by hawkeye116477** [comment]
@krystian3w Zostawiam dla ciebie scrolla, o ile da się coś z tym zrobić.

**Comment by krystian3w** [comment]
Jak nie wymyślę skryptu, to pewnie nic nie zrobię.

**Comment by krystian3w** [comment]
Chyba, że chodzi o webkitowy...

**Comment by krystian3w** [comment]
Coś wymyślę, najwyżej się nadpisze ten najdłuższy, najbardziej na prawo.

**Comment by hawkeye116477** [comment]
@krystian3w No właśnie webkitowy, style chyba odpada, bo Nano odrzuca.

**Comment by krystian3w** [comment]
U mnie w Chrome  z Nano ładnie przechodzi kod w własnych, resetuję na body.

**Comment by hawkeye116477** [comment]
No ok, tylko ten kolor może bym poprawił na standardowy :smile:

**Comment by krystian3w** [comment]
Ja tam nie wiem jaki jest standardowy, szare się nie podobały (jasność / kontrast) to kopiuje twój czarny.

**Comment by hawkeye116477** [comment]
Niby na auto powinno być, ale tutaj coś to chyba nie działa.

**Comment by krystian3w** [comment]
Na auto to chyba wychodzi białe na białym?

**Comment by krystian3w** [comment]
A pop-up jakoś funkcjonalnie wycięty, bo tak to i trzeba by ukryć:

`###postal-code` i tekst przed nim jakoś CSS-em zamaskować?

**Comment by hawkeye116477** [comment]
Już dodałem `kwit.pl###modalPostalCode, .modal-backdrop`

**Comment by krystian3w** [comment]
To trochę lipa :rofl:, chyba tylko skrypt pewnie da radę ubić ten przy 1 wizycir, najlepiej ten ciasteczkowy :cookie:.

**Comment by krystian3w** [comment]
Jak coś to ja przyciski newsletterów docinałem jak otwierały zablokowany pop-up, a ten przykład jest mi obcy co z tym fantem zrobić, zwłaszcza, że tekst jakiś zostanie.

**Comment by hawkeye116477** [comment]
`chyba tylko skrypt pewnie da radę ubić ten przy 1 wizycie`
Jak to? Nie wiem o co się rozchodzi, bo u mnie te reguły wycięły ten popup., nie ma nic przy 1-szej wizycie.

**Comment by hawkeye116477** [comment]
Ah, to chyba jednak powinno zostać, jakby ktoś chciał porównać z lokalnym sklepem.
No chyba, że has/watch-attrs coś pomoże.

**Comment by krystian3w** [comment]
Raczej nie? :persevere:

**Comment by krystian3w** [comment]
A co na to html filtering, są komentarze, to i może w źródle pop-up?

**Comment by hawkeye116477** [comment]
@krystian3w Siedzi wszystko tutaj `kwit.pl/assets/application-20b76485b8c0384ef6607a4accaf59a4.js`, :penguin: zrobi im :cookie:  i po sprawie :smile:.

**Comment by hawkeye116477** [comment]
My z tym nic nie zrobimy, a ten serwis głównie na tym polega, by wpisać kod pocztowy i zrobić porównanie. 
Także odrzucamy, jednak możesz spróbować szczęścia u :penguin:, może on za rok doda :smile:

**Comment by krystian3w** [comment]
lub własne:
```
               userResourcesLocation
```

W Nano Ablocker opcjonalnie:

```
nanoMakeThirdPartyFiltersPrivileged true
      nanoMakeUserFiltersPrivileged true
```

**Comment by krystian3w** [comment]
Prawdopodobnie można użyć:

`no-postal:true` w set-cookie.
