### ISSUE TITLE
kofiup.pl

### ISSUE THREAD

**Issue by xMaap** [FiltersHeroes/PolishAnnoyanceFilters#1576]
![Opera Zdjęcie_2019-04-13_034413_www kofiup pl](https://user-images.githubusercontent.com/36385327/56073050-77584400-5d9e-11e9-99e5-f37f8c319e0f.png)
### Typ elementu/problemu
- [x] Wyskakujące okienko (popup)
- [ ] Newsletter (nie popup)
- [] Powiadomienie push (nie „zgoda na geolokalizację”)
- [] Scrollujący filmik
- [] Inny element (np. widget „następny artykuł”)
- [] Widżet kontaktowy/informacji zwrotnej
- [] Strzałka
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
Chętni mogą zrobić skrypt lub html filtering jak się niby opłaci.

**Comment by krystian3w** [comment]
Do przemyślenia kwestia co jak certyfikat wygasł, jak niby śledzić czy już kupili nowy.

**Comment by krystian3w** [comment]
Nie za dobrze, aplikacje z Google Play wycofano, z iOS jeszcze niby jest.

**Comment by hawkeye116477** [comment]
Na ich FB są wpisy z przed roku, także wątpię, że odnowią certyfikat. Raczej pakują manatki.

**Comment by xMaap** [comment]
To chyba można zamknąć.
