### ISSUE TITLE
blog.oleole.pl

### ISSUE THREAD

**Issue by xMaap** [FiltersHeroes/PolishAnnoyanceFilters#1588]
http://blog.oleole.pl/ranking-pralek-najlepsze-w-lipcu-2015-r/?link=rotator-blog
![Opera Zdjęcie_2019-04-15_204442_blog oleole pl](https://user-images.githubusercontent.com/36385327/56157257-53c01400-5fbf-11e9-8508-e03f845977a3.png)

### Typ elementu/problemu
- [] Wyskakujące okienko (popup)
- [] Newsletter (nie popup)
- [] Powiadomienie push (nie „zgoda na geolokalizację”)
- [] Scrollujący filmik
- [x] Inny element (np. widget „następny artykuł”)
- [] Widżet kontaktowy/informacji zwrotnej
- [] Strzałka
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
Aktualizacja około 24:00 :clock12:
