### ISSUE TITLE
H&M

### ISSUE THREAD

**Issue by krystian3w** [FiltersHeroes/PolishAnnoyanceFilters#1599]
### Typ elementu/problemu
- [X] Wyskakujące okienko (popup)
- [X] Błąd

https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/blob/2c811e715955703109a1c1aa55a2f04a5b8eabdf/PPB/uBO_AG/popupy_suplement.txt#L213

Trzeba by jakoś ogarnąć gryzienie się odblokowania przewijania z tym pop-upem, nie dogadują się...

https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/blob/c4ce1947d8930d29930a66820972426d8d6c7a87/PPB_uBlock_AdGuard.txt#L585-L586

**Comment by hawkeye116477** [comment]
Jakie gryzenie się, jest ok, popup znika po czasie.

**Comment by krystian3w** [comment]
Znika ale za wolno zmniejsz okno na pół i scroll poziomy się robi.

**Comment by krystian3w** [comment]
> No niby tak, ale zmniejsz sobie okno jak masz monitor full hd i taki filtr:
> 
> `##.takeover-wrapper.responsive.modaloverlay`
> 
> i taki efekt:
> 
> > ![obraz](https://user-images.githubusercontent.com/35370833/56909832-5c2d4a00-6aa9-11e9-9911-a3660ff84601.png) |
> > --- |
>

**Comment by hawkeye116477** [comment]
@krystian3w Ale ta reguła jest raczej zbędna, wystarczą te:
`hm.com##.modaloverlay:has(#gdpr-modal)
hm.com##.modal-open, .modal-open body:style(position: static !important; overflow-y: auto !important;)`. 
No chyba, że przy niższych rozdzielczościach coś tam innego się pojawia. Tak czy siak ja tego efektu nie mam.

**Comment by krystian3w** [comment]
Chodzi że atakują na starcie rodem i newsletterem.

**Comment by hawkeye116477** [comment]
@krystian3w No to u mnie tylko RODO, brak newslettera.
