### ISSUE TITLE
tvgo.orange.pl

### ISSUE THREAD

**Issue by xMaap** [FiltersHeroes/PolishAnnoyanceFilters#1605]
Nie wiem jak to zaznaczyć i czy w ogóle się to nadaje, ale też po tym samouczku wyskakuje powiadomienie o RODO czy tam Cookies.
![Zrzut ekranu z 2019-05-12 19-16-04](https://user-images.githubusercontent.com/36385327/57585599-94da1400-74ea-11e9-93bc-9ec398716f69.png)

### Typ elementu/problemu
- [x] Wyskakujące okienko (popup)
- [] Newsletter (nie popup)
- [] Powiadomienie push (nie „zgoda na geolokalizację”)
- [] Scrollujący filmik
- [] Inny element (np. widget „następny artykuł”)
- [] Widżet kontaktowy/informacji zwrotnej
- [] Strzałka
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
Samouczek się raczej nie nadaje, a Orange ma zbitkę 10 lat jak Plus, nie umieją ogarnąć swoich stron.

**Comment by krystian3w** [comment]
Samouczka na moje nawet nie da się wyciąć, tło pod nim że niby jest strona to podpucha, cookies / RODO już w filtrach dev dla uBO / Nano Adblocker / AdGuard.
