### ISSUE TITLE
wyborcza.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#1620]
### Typ elementu
inny element
### Moja konfiguracja 
**System operacyjny:** Linux
**Przeglądarka internetowa:** Mozilla Firefox 67
**Bloker:** uBlock Origin 1.19.6
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
Coś jest za dużo blokowane, bo nie da się wysłać komentarza - przycisk komentarza jest wyszarzony, a przeglądarka wyświetla ciągle info, że czeka na dociągnięcie danych z wyborcza.pl

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Paywall...

**Comment by krystian3w** [comment]
Nie ładować strony po `https`, wtedy działa i ładuje normalnie.

**Comment by krystian3w** [comment]
```
https://mojekonto.wyborcza.pl/account/subscriptions
```

Jakby ktoś wykupił trial i szukał gdzie wyłączyć, by nie zabrali 20 złotych,
