### ISSUE TITLE
braciaprzykawie.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [FiltersHeroes/PolishAnnoyanceFilters#1652]
all

**Comment by hawkeye116477** [comment]
Witaj @KonoromiHimaries, dzięki za zamieszczenie zgłoszenia. Niestety nie podałeś wymaganych informacji z szablonu zgłoszeniowego. Utwórz nowe zgłoszenie ze wszystkimi wymaganymi informacjami z szablonu (szczególnie ważny jest ###Typ elementu), a to ułatwi nam pomoc w rozwiązaniu twojego problemu.
