### ISSUE TITLE
websiteplanet.com

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#1683]
### Typ elementu
popup
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Waterfox 56.2.12
**Bloker:** Nano Adblocker 1.0.0.103
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by hawkeye116477** [comment]
@krystian3w Masz coś tam?

**Comment by krystian3w** [comment]
Mam newsletter w stopce, tyle.

**Comment by krystian3w** [comment]
Może ktoś dezaktywował EasyPrivacy i one XHR przemycają pop-up:

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +2 | \|\|alooma.com/track/ | -- | `www.websiteplanet.com` | 3 | xhr | `https://inputs.alooma.com/track/?data=eyJldmVudCI6ICJtcF9wYWdlX3ZpZXciLCJwcm9wZXJ0aWVzIjogeyIkb3MiOiAiV2luZG93cyIsIiRicm93c2VyIjogIkZpcmVmb3giLCIkcmVmZXJyZXIiOiAiaHR0cHM6Ly93d3cud2Vic2l0ZXBsYW5ldC5jb20vIiwiJHJlZmVycmluZ19kb21haW4iOiAid3d3LndlYnNpdGVwbGFuZXQuY29tIiwiJGN1cnJlbnRfdXJsIjogImh0dHBzOi8vd3d3LndlYnNpdGVwbGFuZXQuY29tL3BsLyIsIiRicm93c2VyX3ZlcnNpb24iOiA2OCwiJHNjcmVlbl9oZWlnaHQiOiA4NjQsIiRzY3JlZW5fd2lkdGgiOiAxNTM2LCJtcF9saWIiOiAid2ViIiwiJGxpYl92ZXJzaW9uIjogIjEuMC4wIiwiZGlzdGluY3RfaWQiOiAiMTZjNDg5ODFlZGFmYy0wNTJhYzg1M2VkNzg1OC00YzMxMjI3Mi0xNDQwMDAtMTZjNDg5ODFlZGI0ZTAiLCIkaW5pdGlhbF9yZWZlcnJlciI6ICJodHRwczovL3d3dy53ZWJzaXRlcGxhbmV0LmNvbS8iLCIkaW5pdGlhbF9yZWZlcnJpbmdfZG9tYWluIjogInd3dy53ZWJzaXRlcGxhbmV0LmNvbSIsIm1wX3BhZ2UiOiAiaHR0cHM6Ly93d3cud2Vic2l0ZXBsYW5ldC5jb20vcGwvIiwibXBfcmVmZXJyZXIiOiAiaHR0cHM6Ly93d3cud2Vic2l0ZXBsYW5ldC5jb20vIiwibXBfYnJvd3NlciI6ICJGaXJlZm94IiwibXBfcGxhdGZvcm0iOiAiV2luZG93cyIsInRva2VuIjogImV5SmhiR2NpT2lKSVV6STFOaUlzSW5SNWNDSTZJa3BYVkNKOS5leUpqYkdsbGJuUk9ZVzFsSWpvaWFXdHViM2RzYjJkNUxYZGxZbk5sYkdWdVpYTmxMVEVpTENKcGJuQjFkRXhoWW1Wc0lqb2laWFpsYm5Seklpd2lhVzV3ZFhSVWVYQmxJam9pU2xOVFJFc2lmUS5xLVRxS21RblFpMWFmRDZpeWF2bEZ4UEdDWUhyczBBSjVIc1E3MnY2TC1RIn19&ip=1&_=1564586024678` |
| +2 | \|\|alooma.com/track/ | -- | `www.websiteplanet.com` | 3 | xhr | `https://inputs.alooma.com/track/?data=eyJldmVudCI6ICJwYWdldmlldyIsInByb3BlcnRpZXMiOiB7IiRvcyI6ICJXaW5kb3dzIiwiJGJyb3dzZXIiOiAiRmlyZWZveCIsIiRyZWZlcnJlciI6ICJodHRwczovL3d3dy53ZWJzaXRlcGxhbmV0LmNvbS8iLCIkcmVmZXJyaW5nX2RvbWFpbiI6ICJ3d3cud2Vic2l0ZXBsYW5ldC5jb20iLCIkY3VycmVudF91cmwiOiAiaHR0cHM6Ly93d3cud2Vic2l0ZXBsYW5ldC5jb20vcGwvIiwiJGJyb3dzZXJfdmVyc2lvbiI6IDY4LCIkc2NyZWVuX2hlaWdodCI6IDg2NCwiJHNjcmVlbl93aWR0aCI6IDE1MzYsIm1wX2xpYiI6ICJ3ZWIiLCIkbGliX3ZlcnNpb24iOiAiMS4wLjAiLCJkaXN0aW5jdF9pZCI6ICIxNmM0ODk4MWVkYWZjLTA1MmFjODUzZWQ3ODU4LTRjMzEyMjcyLTE0NDAwMC0xNmM0ODk4MWVkYjRlMCIsIiRpbml0aWFsX3JlZmVycmVyIjogImh0dHBzOi8vd3d3LndlYnNpdGVwbGFuZXQuY29tLyIsIiRpbml0aWFsX3JlZmVycmluZ19kb21haW4iOiAid3d3LndlYnNpdGVwbGFuZXQuY29tIiwicGFnZXZpZXdfaWQiOiAxNTY0NTg2MDIzNjkwLCJpZCI6ICI5Mjg3IiwibGFuZyI6ICJwbCIsInRpdGxlIjogIldlYnNpdGUgUGxhbmV0IC0gTWllanNjZSBkbGEgd3N6eXN0a2ljaCBwb3RyemViIFR3b2plaiB3aXRyeW55IiwidHlwZSI6ICJwYWdlIiwidXNlckFnZW50IjogIk1vemlsbGEvNS4wIChXaW5kb3dzIE5UIDEwLjA7IFdpbjY0OyB4NjQ7IHJ2OjY4LjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvNjguMCIsInNwbGl0Q3VycmVudFVybCI6IHsiaG9zdCI6ICJodHRwczovL3d3dy53ZWJzaXRlcGxhbmV0LmNvbS9wbC8iLCJwYXJhbXMiOiB7IiI6ICJ1bmRlZmluZWQifX0sInRva2VuIjogImV5SmhiR2NpT2lKSVV6STFOaUlzSW5SNWNDSTZJa3BYVkNKOS5leUpqYkdsbGJuUk9ZVzFsSWpvaWFXdHViM2RzYjJkNUxYZGxZbk5sYkdWdVpYTmxMVEVpTENKcGJuQjFkRXhoWW1Wc0lqb2laWFpsYm5Seklpd2lhVzV3ZFhSVWVYQmxJam9pU2xOVFJFc2lmUS5xLVRxS21RblFpMWFmRDZpeWF2bEZ4UEdDWUhyczBBSjVIc1E3MnY2TC1RIn19&ip=1&_=1564586024676` |
</details>

**Comment by krystian3w** [comment]
I chyba trzeba by Waterfox na próbę do testu, może legacy dostają inny kod.

**Comment by hawkeye116477** [comment]
@krystian3w Bardziej podejrzewałbym, że @blocker999 złapał jakiegoś wirusa. Bo nawet bez adblockera nie widzę tam popupa.

**Comment by krystian3w** [comment]
@blocker999:

1. https://pl.malwarebytes.com/adwcleaner/
2. https://pl.malwarebytes.com/mwb-download/thankyou/
