### ISSUE TITLE
www.money.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#1690]
### Typ elementu
popup,push
### Link bezpośredni 
`https://www.money.pl/`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Mozilla Firefox 58
**Bloker:** uBlock Origin 1.21.0
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
Wyskakujące okno cookies + wkurzający wielki baner reklamowy u góry strony, fajnie by było oba te elementy ukryć.

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
RODO w dodatku: https://addons.mozilla.org/pl/firefox/addon/polish-cookie-consent/

**Comment by krystian3w** [comment]
Reklamy WP raczej nie tą listą.

**Comment by hawkeye116477** [comment]
@krystian3w Nie ma co myśleć, to do @MajkiIT, a tak w zasadzie to ja tam nie widze nawet tej reklamy.

**Comment by krystian3w** [comment]
Na telefonie ją widać, widać skrypt adama na nią zawodzi z ARM.

**Comment by krystian3w** [comment]
Co do przemyślenia to może nowy sposób na push na money niby testują.

**Comment by hawkeye116477** [comment]
@krystian3w Tam nie ma pusha, zgłaszający nawet w dodatkowych informacjach nie wspomniał, więc raczej obstawiam, że się pomylił.

**Comment by krystian3w** [comment]
A push na Onet doblokować czy olać, na telefonie nawala.

**Comment by hawkeye116477** [comment]
@krystian3w Doblokuj.

**Comment by hawkeye116477** [comment]
`Na telefonie ją widać, widać skrypt adama na nią zawodzi z ARM.`
@krystian3w No to chyba ja mam lepszy fon, bo tego nie widzę :smile:.
#xiaomilepsze
