### ISSUE TITLE
sportowefakty.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#1691]
### Typ elementu
popup,inny element
### Link bezpośredni 
`https://sportowefakty.wp.pl`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 76.0.3809.100 
**Bloker:** Nano Adblocker 1.0.0.123
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
można zablokować sam popup ale nie mogę zablokować tej mgły

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by hawkeye116477** [comment]
@olegwukr Job for you.
