### ISSUE TITLE
wp.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#1696]
### Typ elementu
popup
### Moja konfiguracja 
**System operacyjny:** Mac
**Przeglądarka internetowa:** Google Chrome 56.0
**Bloker:** uBlock Origin 1.22.2
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
wp znowu wykrywa filtry

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by hawkeye116477** [comment]
To nie do nas, oni zresztą codziennie coś zmieniają, więc wątpię, że ktokolwiek to naprawi.
