### ISSUE TITLE
onet.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#1716]
### Typ elementu
inny element
### Link bezpośredni 
`https://www.onet.pl/`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Mozilla Firefox 70
**Bloker:** Adblock Plus 3.7
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
Biała luka pomiędzy wiadomościami a pogodą, po prawej stronie.

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by hawkeye116477** [comment]
@MajkiIT Chyba to coś dla ciebie.

**Comment by krystian3w** [comment]
Tego się nie da "ruszyć", nie bawmy się w Norwega co sobie on każdy box rozciąga jak obok była brzydka reklama.
