### ISSUE TITLE
animezone.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#1724]
### Typ elementu
błąd
### Link bezpośredni 
`https://www.animezone.pl/dodaj`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 78
**Bloker:** uBlock Origin 1.23.0
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
CAPTCHA nie działa

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by hawkeye116477** [comment]
@krystian3w Zostawiam dla ciebie do zbadania, niby wujek zezwala na `visibility: hidden`, więc raczej powinno być ok...

**Comment by krystian3w** [comment]
U mnie też OK, chyba że zalogowaniu muszą zaznaczać?

![obraz](https://user-images.githubusercontent.com/35370833/68994984-05426300-0889-11ea-9a09-93bca55cb9f0.png) |
--- |

**Comment by krystian3w** [comment]
Jeszcze też może być, że Windows walnięty lub Avira walnięta u użytkownika.
