### ISSUE TITLE
Pytanie o kierunek dalszego rozwoju paczki

### ISSUE THREAD

**Issue by blocker999** [FiltersHeroes/PolishAnnoyanceFilters#173]
Zapraszam Wszystkich do wypowiedzenia się nt; statycznych obrazków, blokować nie blokować, część z nich, które i dlaczego?

Oto trzy przykłady:

![allegro - smieci](https://user-images.githubusercontent.com/23176832/31288670-2f3fd0de-aac6-11e7-859b-969e9d83cee2.png)

![mgsm - smieci](https://user-images.githubusercontent.com/23176832/31288679-3e70138e-aac6-11e7-96cc-a6dfea80353b.png)

![speed](https://user-images.githubusercontent.com/23176832/31288708-5a567958-aac6-11e7-9612-3511052c4113.png)

**Comment by gomoku** [comment]
Przy okazji kolejne pytanie, czy takie coś też blokować:

![](https://s3.dodajfote.pl/2017/10/07/cosmoppolitan_popupf0932204b831e92e.png)

![](https://s3.dodajfote.pl/2017/10/07/brogshop_popup6261d08a6ded8801.png)

**Comment by blocker999** [comment]
@gomoku  Ja bym to zostawił bo i tak ludziom tam zaglądającym to obojętne no ale mogę się mylić dlatego o opinie poprosze @hawkeye116477

**Comment by hawkeye116477** [comment]
Też bym to zostawił. No nie przesadzajmy, nie usuwajmy oznakowań wiekowych.
Ja tam zrozumiałem raczej, że @gomoku wstrzymuje się od głosu.

**Comment by gomoku** [comment]
> @blocker999: Ja bym to zostawił bo i tak ludziom tam zaglądającym to obojętne no ale mogę się mylić 
> @hawkeye116477: Też bym to zostawił. No nie przesadzajmy, nie usuwajmy oznakowań wiekowych.

A gdzie jakieś uzasadnienie? Bo tak i już ? Bo tak i tyle? Bo ma być po waszemu ? Bo wy tupnęliście nogą? A może bo macie 50cm w bicepsach? Bo mogę skontrować to takimi samymi argumentami bez uzasadnienia, odwróconymi o 180 stopni, a takie argumenty, które da się tak łatwo odwrócić i odesłać do nadawcy to nie są prawdziwe argumenty:

> Ja bym to usunął bo i tak ludziom tam zaglądającym to obojętne no ale mogę się mylić 
> Też bym to usunął. No nie przesadzajmy, nie zostawiajmy oznakowań wiekowych.

I są słowa przeciwko słowom, w tym momencie nasze argumenty się  zrównały i zneutralizowały i wyparowały jak para wodna, jest remis / pat / impas, racji nie macie, bo mielicie jak krowy ozorami, a realnych argumentów żadnych, jaki poziom argumentów taki poziom dyskusji.

@blocker999 nie wywróżyłeś tego z fusów / lanego wosku / szklanej kuli prawda? Więc jeśli możesz to podaj w końcu ten link do tej ankiety/sondażu, którą przeprowadziłeś - i jaka była próbka - 1000 osób?, a jeśli nie przeprowadziłeś, to skąd znasz opinie innych ludzi, no bo raczej nie czytasz ludziom telepatycznie w myślach?, a jeśli nie znasz to uzasadnij dlaczego myślisz, że ludziom to obojętne, bo na pewno nie dlatego, że ty tak napisałeś, bo taką logiką to zaraz napiszesz, że ludziom to obojętne czy Fanta czy Pepsi, tylko skąd ty możesz znać czyjeś gusta.

> @blocker999: Co do mojego pytania, to rozumiem że jesteś za?.

Czyli jest tak, agresywne popup wiekowe wam nie przeszkadzają, a statyczne obrazki przeszkadzają, tzn. raczej powinno być odwrotnie? A może mi się to śni, może ktoś mnie uszczypnie?

**Comment by blocker999** [comment]
@gomoku to że niewdaje się w dyskusje to wynika z braku czasu a nie argumentów, ale dobra podam Ci przykład z życia : przyjeżdża do Ciebie kuzynka z dzieciakiem sześcioletnim i masz takie reguły by usuwały te oznaczenia , oczywiście otym zapominasz a młody dajmy wchodzi na co chce i ogląda a obok jego matka no i ja pale się ze wstydu i co mam jej powiedzieć że to tylko wykop.pl a to że sam wszedł to już niemoja wina a to że niebyło oznaczeń wiekowych to przecież dla mojej wygody.
Przecież @gomoku  masz zakładke Moje filtry i tam se dodawaj co chcesz bo ja biore pod uwage każdą ewentualność a nie Twe zachcianki.

**Comment by gomoku** [comment]
@blocker999 przecież @gomoku masz zakładke Moje filtry i tam se dodawaj co chcesz bo ja biore pod uwage każdą ewentualność a nie Twe zachcianki.

Nie ma tu żadnych moich zachcianek, więc nie imputuj mi ich, bo ja do nikogo do niczego nie zmuszam, zachcianki to są z waszej strony - dalej na końcu o tym napiszę, nawet nie wyraziłem jeszcze swojego głosu za czy przeciw, a jedynie poruszyłem dyskusję, żeby wprowadzić do niej także inne argumenty - bardziej techniczne.

Twój przykład z życia nie bazuje na analizie technicznej, chodzi o to, że podobny przykład z życia można podać także odnośnie blokowania komunikatów o ciasteczkach, chodziło bardziej o pewną logikę i konsekwencję, że zarówno wyskakujące okienka o ciasteczkach jak i o potwierdzaniu wieku to jest ten sam element, który o czymś informuje i to pod rygorem prawnym (chociaż nie jestem pewien czy te komunikaty wiekowe są pod rygorem prawnym), więc albo się blokuje komunikaty zarówno ciasteczkowe jak i wiekowe, albo żadne, wóz albo przewóz, bo sama argumentacja przykładami z życia, nie twierdzę, że jest zła, a może nawet lepsza, ale nie jest jedyna, bo jeśli źle jest blokować komunikaty wiekowe bo coś tam (to co napisałeś), to tak samo można podać przykład z życia, że blokowanie komunikatów o ciasteczkach też jest złe, bo potem ktoś chodząc po stronach nie będzie świadomy, że strona zapisuje / zbiera / przechowuje o nim informacje, tak samo jak dziecko nie będzie świadome na jaką stronę wchodzi, także znowu argumenty się zrównują bo w przypadku blokowania obydwu komunikatów jest skutek uboczny - brak świadomości, który może skutkować niepożądanymi skutkami ubocznymi po wejściu na stronę, więc z punktu widzenia techniczno-prawnego dlaczego tylko jedne komunikaty mają być blokowane a drugie nie? Bo przepis to przepis, ten czy tamten, wszystkie są sobie równe, i albo się stosuje do wszystkich albo żadnych, bo jeśli się wybiera które przepisy stosować i wnika w ich analizę, to schodzi się z technicznego podejścia, do życiowego-politycznego podejścia, czyli tworzy się samowolkę i własne prawo, zamiast stosować się do tego, które już zostało stworzone. I właśnie to nazwałbym waszymi politycznymi zachciankami typu: wybieranie sobie który przepis jest ok, a który nie, do którego się stosować, a do którego nie, na postawie własnego widzimisię i samowolczej inicjatywy ustawodawczej i prawnej, ale to wtedy chyba powinniście zostać politykami/prawnikami i tworzyć prawo w parlamencie, tam wasze zachcianki zostaną wysłuchane i wasze opinie - który przepis jest lepszy, który gorszy? Tzn czy nie pomyliliście repozytorium z parlamentem?

Oczywiście jeśli ktoś chce to może stosować argumentację pozatechniczną, na podstawie przykładów z życia i poziomu szkodliwości efektu ubocznego, że wg. niego np. gorsze jest to, że małoletni wejdzie na stronę porno, niż to, że ktoś wejdzie na stronę, która go będzie śledziła i gromadziła o nim informacje za pomocą ciasteczek, tylko, że to już są prywatne osądy i ważenie przepisów i wcielanie się w rolę polityka, a przecież z techniczno-prawnego punktu widzenia przepis to przepis, i z punktu uwidzenia twórców filtrów oraz osób korzystających z tych filtrów, czyli surfujących po internecie, wszyscy będą zgodni, że obydwa wyskakujące typy komunikatów są tak samo nachalne i uciążliwe. Podałeś przykład z dzieckiem, ale jako, że nie jestem pewien czy te komunikaty wiekowe są prawnie nakazane, to czy nie jest taki tok myślenia poprawny, że to nie dziecko kupiło sobie komputer, i nie dziecko podłączyło go do internetu i nie dziecko zainstalowało adblockera i nie dziecko zainstalowało listę filtrów, tylko osoba dorosła, która przecież wie co robi, tzn wie, że jeśli instaluje listę filtrów w której opisie jest napisane, że ta lista blokuje elementy takie jak nachalne okienka i komunikaty itp. to na pewno wie, że wyskakujące komunikaty np. wiekowe należą właśnie do takich elementów, ewentualnie może pochodzić dla próby po kilku stronach i zobaczyć jakie elementy są blokowane, więc w czym problem? Czy to nie problem tej osoby/opiekuna, żeby pilnowała , której listy używa mając dziecko, albo np. dezaktywowała listę przed odejściem od komputera lub po prostu używała oprogramowania do blokowania treści dla niepełnoletnich? ( no właśnie - po co i dla kogo w takim razie są te programy typu pakiety ochronne/antywirusowe z modułami do blokowania treści dla niepełnoletnich?) Na koniec, podajesz przykład z dziećmi, a dorośli to już nie istnieją na tym świecie? A może zapomniałeś o nich? Oni mają znosić te nachalne komunikaty wiekowe? Bo nie da się w tym przypadku zjeść ciastka i mieć ciastka, albo z tymi komunikatami będą musieli się użerać dorośli, albo z ich brakiem będą musiały użerać się dzieci. No pewnie napiszesz, że dzieci ważniejsze, ale z drugiej strony dorosłych jest x razy więcej, więc który argument ważniejszy - mniej osób ucierpi bo dzieci ale ważniejszych, czy więcej osób ucierpi dorosłych ale mnie ważnych. Który sposób argumentacji/miarowania jest bardziej prawidłowy? 

I tyle, przedstawiłem tylko pewną alternatywną kwestię, nikogo do niczego nie zmuszam, każdy swój głos odda w oparciu o swój sposób argumentowania, jaka będzie finalna decyzja i co z tego wyniknie nie wiem, ja swojego głosu na razie nie oddaję, póki dyskusja trwa.

**Comment by gomoku** [comment]
Jak chcecie, ja nie mam zdania:

- technicznie komunikaty ciasteczkowe i te wiekowe to to samo i są tak samo natrętne
- niby musi być komunikat żeby dziecko nie wlazło na porno, ale w telewizji gdzie lecą w biały dzień filmy sensacyjne, w których są morderstwa, pobicia i latają trupy, to już jakoś nie musi? Trochę to dziwne, bo raczej morderstwa i pobicia są drastyczniejsze niż seks.

**Comment by gomoku** [comment]
@blocker999 a ja skontruje i też ci podam przykład z życia: ktoś chce wejść na strony porno i musi użerać się z natrętnymi komunikatami...

**Comment by gomoku** [comment]
> @hawkeye116477: Ja tam zrozumiałem raczej, że @gomoku wstrzymuje się od głosu.

Nom, nie mam zdania co do jakichkolwiek elementów poruszonych w tym wątku.

**Comment by gwarser** [comment]
Jak jest duża wstawka między artykułem i komentarzami, to można usunąć (czasami tak robię na blogach które subskrybuje).

Osiemnastki zostawić.

**Comment by hawkeye116477** [comment]
@blocker999 Ok, w takim razie bierzemy się za usuwanie.

**Comment by blocker999** [comment]
@hawkeye116477 OK, ale tylko te pomiędzy artykułem a komentarzami czy też pozostałe?

**Comment by hawkeye116477** [comment]
@blocker999 Co do pozostałych, to podaj może jakąś przykładową stronę i screen.

**Comment by gwarser** [comment]
Te które przeszkadzają :) Jak sobie siedzi gdzieś na dole i nie ma potrzeby przy normalnym używaniu strony zaglądania na dół, to niech zostanie.

**Comment by blocker999** [comment]
@hawkeye116477 Przykłady podałem w pierwszym komentarzu, wiec tak 1 - to allegro artykuły pod aukcjami, ja osobiście uważam to za zbędne bo jak ktoś będzie chciał to poczytać to itak to znajdzie.
2 - mgsm pod artykułem, to samo co allegro, do dyskusji czy blokować czy nie?
3 - to spidersweb, ale to akurat jest do usunięcia bo akurat jest pomiędzy.
No ale co dalej z tą przykładową 1 i 2 to ja niewiem, decyzja należy do Ciebie.

**Comment by hawkeye116477** [comment]
@blocker999 Mgsm i spidersweb już dzisiaj dodałem. 
A co do Alledrogo to nie wiem, może to usunąć, ja tam i tak tego nie czytam.
Przy okazji zapytam to po prawej też blokujemy (może Cię również zainteresować) ?
https://allegro.pl/artykul/black-white-czyli-interesujace-wnetrze-w-bieli-i-czerni-115511?bi_s=internal&bi_c=115511&bi_m=mpage-dom-i-zdrowie&bi_term=odmien-swoje-wnetrze

**Comment by blocker999** [comment]
@hawkeye116477 Niewiem jak chcesz w sumie to nielata a ja wchodze tam tylko aby coś kupić a nie czytać, albo ewentualnie zgłoś to do alleblocka.

**Comment by blocker999** [comment]
A jeszcze natknołem się na takie coś:

![nm](https://user-images.githubusercontent.com/23176832/32409362-8a00aa7a-c1aa-11e7-8b51-9266300faec9.png)

blokować?

**Comment by hawkeye116477** [comment]
Na gazeta.pl też są takie wielkie na górze. Nie wiem, można by to zablokować. Jeszcze poprosiłbym @gwarser o opinię.

**Comment by gwarser** [comment]
Naszemiasto - raczej nie, to jest jednak link do artykułu i tylko na głównej stronie.
Hmmm - dziwne. Tu jest http://warszawa.naszemiasto.pl/artykul/warszawa-imprezy-3-5-listopada-polecamy-najciekawsze,4295542,galop,t,id,tm.html a tu nie ma http://warszawa.naszemiasto.pl/magazyn/artykul/trzy-najlepsze-koncerty-listopada-i-trzy-gatunki-muzyczne,4297890,t,id.html a za to mi jakaś kreska jeździ przy przewijaniu.

**Comment by blocker999** [comment]
@hawkeye116477 Co do ilości kosmetycznych w PB to fakt jest ich zadużo gdyż są w liście pozostałości z początku listy które można usunąć bo albo blokują jedną lub dwie strony albo niewiadomo doczego i z której strony a może są już bez użyteczne bo strona wygasła, niewiem więc takie śmieci możesz śmiało usunąć a codo pozostałych to będziemy z czasem robić ogólne, zresztą zobaczymy.

@gwarser ja w linkach do artykułów też niewidze nic złego tylko chodzi mi o to że one są nad headerem, niewiem ale zastanów się bo ja nasiłe niezamieżam ich blokować.

**Comment by hawkeye116477** [comment]
@blocker999 @gwarser Tutaj jest A o tym czytaliście oraz Czytaj również i Czytaj więcej.
https://www.chip.pl/dzieje-si%C4%99/kalkulator-iphoneie-umie-dodawac/
Czyli co A o tym czytaliście - wywalamy, a czytaj również i czytaj więcej zostawiamy czy też chowamy?

**Comment by gwarser** [comment]
>A ta kreska to pasek postępu, takie cuda też blokować?

No jak wisi w powietrzu, bo nagłówek jest przypięty, to tak.

@hawkeye116477 tak jak mówisz.

**Comment by hawkeye116477** [comment]
@gwarser Ok, ale co w takim razie z tym po boku _czytaj również i czytaj więcej_ - zostawić to czy schować?

**Comment by gwarser** [comment]
Zostawić.

**Comment by blocker999** [comment]
@hawkeye116477 Ok boczne zostawiamy bo to jest wtopione w strone ani nielata, natomiast @gwarser co z tymi nad headerem?

**Comment by gwarser** [comment]
@blocker999 zobaczymy co tam będzie jutro.

**Comment by blocker999** [comment]
@gwarser OK

**Comment by hawkeye116477** [comment]
A na mobilitynews.pl to coś na górze chowamy?
`mobilitynews.pl##.swiper-wrapper`

**Comment by blocker999** [comment]
@hawkeye116477 Ja bym to wywalił tak samo jak art.na górzze na naszemiasto.pl ale poczekajmy na opinie @gwarser

**Comment by gwarser** [comment]
Można wywalić. Kto z Warszawy i mu to potrzebne?

**Comment by mat41997** [comment]
@hawkeye116477 na oznakowania wiekowe to można zrobić inną listę. w listach filtrów dla dorosłych, tylko kto się podejmie ich wsparcia?

**Comment by hawkeye116477** [comment]
@everyone A co myślicie o takich elementach, blokować czy nie?
https://gamedot.pl/
![screenshot_20171208_123306](https://user-images.githubusercontent.com/19818572/33764257-f6adfa6e-dc13-11e7-9be4-729fbb3b51fa.png)

![screenshot_20171208_123238](https://user-images.githubusercontent.com/19818572/33764244-e74976ac-dc13-11e7-8e2e-2fe3053d7810.png)

![screenshot_20171208_123135](https://user-images.githubusercontent.com/19818572/33764230-da9e95e0-dc13-11e7-8e0c-5898477a582f.png)

**Comment by blocker999** [comment]
@hawkeye116477 Niewiem, ja bym zostawił, choć niekturzy by cały net zablokowali, zapytaj @mat41997 on chciał reklamy wewnętrzne blokować to może i to mu niepasuje najlepiej niech utworzy paczke z elementami wewnetrznymi, no ale może ktoś jeszcze się wypowie.

**Comment by hawkeye116477** [comment]
@blocker999 Ok, czyli to też raczej niekwalifikuje się do PPB tylko do wewnętrznych?
wolnosc24.pl
![screenshot_20171208_175327](https://user-images.githubusercontent.com/19818572/33776147-c6e06222-dc40-11e7-8c9e-6cf9969a5f59.png)
![screenshot_20171208_175413](https://user-images.githubusercontent.com/19818572/33776172-d6b05432-dc40-11e7-97c8-5b295b7cca20.png)
![screenshot_20171208_175437](https://user-images.githubusercontent.com/19818572/33776186-e080ba42-dc40-11e7-80a8-c4b66145f143.png)

**Comment by mat41997** [comment]
co do 18+ to, to można zrobić w oddzielnych filtrach przeznaczonych dla dorosłych.

**Comment by mat41997** [comment]
moje filtry wewnętrzne są tworzone jako dodatek do polskich filtrów adblock i ublock.

**Comment by mat41997** [comment]
co do rozwoju paczki to ja bym zmienił jej nazwę na jakąś mniej wprowadzającą w błąd.

**Comment by mat41997** [comment]
@hawkeye116477 już to blokuje w filtrach wewnętrznych.

**Comment by hawkeye116477** [comment]
No to może po prostu Polskie filtry annoyances albo elementów irytujących.

**Comment by blocker999** [comment]
@hawkeye116477 może warto połączyć paczki?

No i pytanie czy @mat41997 jest zainteresowany współsprawcą?

**Comment by mat41997** [comment]
@blocker999 co będę w stanie zrobić to zrobię.

**Comment by mat41997** [comment]
@blocker999 połączyć paczki? ale o co konkretnie masz na myśli?

a ) chcesz zrobić składanki z paczek? coś jak mają tutaj? -jak najbardziej-
https://github.com/StevenBlack/hosts

b ) chcesz przemigrować z listą filtrów pb+ do repo majkiego? -pytaj majkiego-

c ) chcesz abym ja z wewnętrznymi do ciebie przemigrował? -no to odpada-

**Comment by hawkeye116477** [comment]
@blocker999 Ale PopupBlocker z czym połączyć?

**Comment by blocker999** [comment]
@hawkeye116477 z wewnetrzymi, choć chyba lepiej będzie tak jak jest, co otym sądzisz?

**Comment by mat41997** [comment]
@blocker999 co myślisz o wspólnym discordzie?
http://ds.certyficate.it

**Comment by blocker999** [comment]
@mat41997 najlepiej niech każdy tworzy osobno.

**Comment by hawkeye116477** [comment]
@blocker999 Ale przecież sam mówiłeś, że nie chcesz blokować tamtych elementów. Więc fuzja raczej odpada. Ale co do nazwy no to chyba faktycznie przydałoby się zmienić, bo przecież blokujemy nie tylko popupy, a PLUS to jakoś chyba nie za bardzo podkreśla.

> najlepiej niech każdy tworzy osobno
Dlaczego? Kanały na czacie masz osobne do każdego filtra, zrobiłem osobny do PPB.

**Comment by blocker999** [comment]
@hawkeye116477 Dobra z tą fuzją to chyba się pośpieszyłem bo niekażdy chce wszystko a elementy wewnętrzne zgłaszaj @mat41997.
A propozycje nowej nazwy zawsze możesz podać meilowo.
Jeśli chodzi o discard to rób jak chcesz ale bezemnie bo ja niemam czasu.

**Comment by hawkeye116477** [comment]
@blocker999 Ok.

**Comment by blocker999** [comment]
@hawkeye116477 Zobacz maila i zabieramy się do roboty

**Comment by hawkeye116477** [comment]
@blocker999 Ok

**Comment by blocker999** [comment]
@hawkeye116477 Mail przeczytany ?

**Comment by hawkeye116477** [comment]
@blocker999 Tak.

**Comment by blocker999** [comment]
@hawkeye116477 Co zrobić z tego typu scrollującymi dotacjami ?, dopóki niebyło paczki @KonoromiHimaries to było jasne że blokować a teraz.

![kresy](https://user-images.githubusercontent.com/23176832/34539665-b478cc32-f0d1-11e7-8243-090ac7c4ba6a.png)

**Comment by KonoromiHimaries** [comment]
@blocker999 też blokować, najwyżej moje filtry dotacyjne będą wymagać waszych.

**Comment by blocker999** [comment]
@KonoromiHimaries Takich wypadków jest bardzo mało więc można je dodać do dwóch paczek, łączenie niewchodzi wgre bo dla mnie dotacje mogą być a co do krytykipolitycznej to niewiem , może @hawkeye116477  się wypowie.

**Comment by hawkeye116477** [comment]
@blocker999 @KonoromiHimaries Scrollujące dotacje dodamy do Polskich filtrów elementów irytujących, natomiast inne dotacje zostawimy dla @KonoromiHimaries, ale scrollujące @KonoromiHimaries może też dodać do swojej paczki.
