### ISSUE TITLE
antyweb.pl

### ISSUE THREAD

**Issue by xMaap** [FiltersHeroes/PolishAnnoyanceFilters#1730]
![Zrzut ekranu z 2019-12-07 22-01-03](https://user-images.githubusercontent.com/36385327/70380571-9a42f400-193d-11ea-840f-92c01be917b8.png)

**Comment by krystian3w** [comment]
Być może już MajkiIT wyciął jako reklama i dało się sieciowo?

**Comment by hawkeye116477** [comment]
Linki są do innych sklepów, więc możnaby to uznać za reklamę. Tak czy siak, najwyraźniej Majk już to wyciął.
