### ISSUE TITLE
roztocze.net/pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#1731]
### Typ elementu
popup,inny element
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Vivaldi 2.9.1705.41
**Bloker:** Nano Adblocker 1.0.0.131
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
@olegwukr strona ma komunikat anty-adblock w nagłówku.

**Comment by krystian3w** [comment]
`inne element` nie widzę na stronie, niech Jaworowicz znajdzie.

**Comment by hawkeye116477** [comment]
To może trzeba zrobić screenshot jako obowiązkowy

**Comment by krystian3w** [comment]
Nie, bo wkleją pierwszy lepszy, a przy wymogu równym "ile 🐦 zaznaczonych" to oleją próbę zgłoszenia lub zrobią 6 kopii obrazka (AdGuard np. weryfikuję nazwę/ścieżkę wgrywanego pliku by ktoś nie wgrał dwa razy tego samego - widać cwaniaczki wgrywały).

**Comment by hawkeye116477** [comment]
@krystian3w U nas można tylko jeden niby, no chyba, że sami wejdą na imgur i wkleją link.

**Comment by krystian3w** [comment]
Tu by nie pomogło, wkleją pop-up a drażniący element będzie trzeba namierzyć w ciemno.

**Comment by blocker999** [comment]
" inne element nie widzę na stronie, niech Jaworowicz znajdzie "

@krystian3w przy zamykaniu, komunikat masz ?

**Comment by krystian3w** [comment]
To dalej pop-up...

**Comment by krystian3w** [comment]
To do przemyślenia czy EI ma dalej wycinać reklamę TXM (Biedronka).

![obraz](https://user-images.githubusercontent.com/35370833/70463236-d05ab200-1abc-11ea-9a08-4303eb2890dc.png) |
---|

Powodzenia jak chcecie robić z 40 filtrów z `abp-has` i każdy z unikalnymi cyframi i generyk u Majkela zapobiegawczo.

**Comment by krystian3w** [comment]
I opcjonalnie czy `inne.txt` wzbogacić o blokowanie reakcji:

![obraz](https://user-images.githubusercontent.com/35370833/70463442-334c4900-1abd-11ea-90c6-769ed3d8ca59.png)

i Jak duże muszą być, do uznania za drażniące, np. jak mają wykres to won z nimi, nie ma to mogą zostać.

**Comment by blocker999** [comment]
@krystian3w dziś niemam tego" pożegnalnego komunikatu  " TXM do @MajkiIT,  " inne " skonsultuj z @hawkeye116477 a pozostałe elementy według własnego uznania.

**Comment by krystian3w** [comment]
Pożegnalny na Roztoczu wycinany jest od około 20 godzin.

"Inny element" to pełno prawny pop-up (wielki z tłem).

**Comment by krystian3w** [comment]
Odrzucenie, bo reklama.

Zatwierdzonie, bo pop-up śledzący opuszczenie obszaru strony (/ brak aktywności).
