### ISSUE TITLE
filmweb.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#1745]
### Typ elementu
popup
### Link bezpośredni 
`https://www.filmweb.pl/film/Pustynia+Po%C5%82udniowa-2007-410237`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome  78.0.3904.108
**Bloker:** Nano Adblocker Nano Adblocker v1.0.0.133
**Używane filtry:** 
Nano Defender Integration​​​​​użytych 2478 z 2646​​​​
uBlock filters​​​​​użytych 18 569 z 19 241​​​​
uBlock filters – Annoyances​​​​​użytych 2780 z 2826​​​​
uBlock filters – Badware risks​​​​​użytych 781 z 819​​​​
uBlock filters – Privacy​​​​​użytych 158 z 175​​​​
uBlock filters – Resource abuse​​​​​użytych 94 z 113​​​​
uBlock filters – Unbreak​​​​​użytych 1200 z 1278​​​​
Reklamy (3/5)
Adblock Warning Removal​​​​​użytych 692 z 730​​​​
AdGuard Base​​​​​użytych 30 855 z 31 150​​​​
EasyList​​​​​użytych 86 585 z 87 658​​​​
Prywatność (3/3)
AdGuard Tracking Protection​​​​​użytych 8429 z 8492​​​​
EasyPrivacy​​​​​użytych 12 951 z 17 752​​​​
Fanboy's Enhanced Tracking List​​​​​użytych 3180 z 3393​​​​
Domeny ze złośliwym oprogramowaniem (4/4)
Malvertising filter list by Disconnect​​​​​użytych 2683 z 2738​​​​
Malware Domain List​​​​​użytych 1102 z 1105​​​​
Malware domains​​​​​użytych 26 837 z 26 863​​​​
Spam404​​​​​użytych 6927 z 7006​​​​
Elementy irytujące (5/6)
AdGuard Annoyances​​​​​użytych 23 802 z 24 018​​​​
Anti-Facebook​​​​​użytych 49 z 68​​​​
EasyList Cookie​​​​​użytych 0 z 16 338​​​​
Fanboy's Annoyance​​​​​użytych 53 577 z 55 921​​​​
Fanboy's Social​​​​​użytych 0 z 26 320​​​​
Wielofunkcyjne (3/4)
Dan Pollock's hosts file​​​​​użytych 13 619 z 14 345​​​​
hpHosts' Ad and tracking servers​​​​​użytych 41 008 z 45 735​​​​
Peter Lowe's Ad and tracking server list​​​​​użytych 1071 z 3247​​​​
Regiony, języki (1/35)
POL: Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda​​​​​użytych 6466 z 6594​​​​
Własne (5/6)
KAD - Przekręty​​​​​użytych 11 522 z 11 522​​​​
NoCoin Filter List​​​​​użytych 1222 z 1222​​​​
Polish Privacy Filters​​​​​użytych 120 z 120​​​​
Polskie Filtry RODO-Ciasteczkowe​​​​​użytych 6033 z 6038​​​​
Polskie Filtry Społecznościowe​​​​​użytych 6687 z 6687​​​​
Importuj...
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by hawkeye116477** [comment]
A co jest napisane w ramce? Proszę czytać uważnie, my nie zajmujemy się takimi sprawami.
