### ISSUE TITLE
kobieta.onet.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#1799]
### Typ elementu
scrollujący filmik
### Link bezpośredni 
`https://kobieta.onet.pl/koronawirus-dodatkowe-zalecenia-higieniczne-na-czas-kwarantanny/ewcm7q7`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Vivaldi 2.0.1309.42
**Bloker:** AdGuard 3.3.8
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Coś uszkadza video, może namierzę filtr.

**Comment by krystian3w** [comment]
A co do działania filtrów chyba to samo co z: #1801
