### ISSUE TITLE
strefabiznesu.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#1800]
### Typ elementu
scrollujący filmik
### Link bezpośredni 
`https://strefabiznesu.pl/koronawirus-biedronka-wprowadza-zmiany-w-swoich-sklepach-nowe-godziny-otwarcia-oraz-plyn-do-dezynfekcji-dla-klientow/ar/c3-14865095`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Vivaldi 2.0.1309.42
**Bloker:** AdGuard 3.3.8
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Mnie działa:

`||ppstatic.pl/*/js/*/article/sticky-video.js`

https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/blob/1e77b7554770c5f036e02f052a9efa83a959f09f/PPB/scroll_film.txt#L25

#1801
