### ISSUE TITLE
businessinsider.com.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#1801]
### Typ elementu
scrollujący filmik
### Link bezpośredni 
`https://businessinsider.com.pl/finanse/handel/koronawirus-w-polsce-polacy-ruszyli-do-sklepow/typgj0e`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Vivaldi 2.0.1309.42
**Bloker:** AdGuard 3.3.8
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
mnie działa:

```
businessinsider.com.pl##.player-floating, .player-move-up
```

https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/blob/1e77b7554770c5f036e02f052a9efa83a959f09f/PPB/scroll_film.txt#L2

Vivaldi ma inny HTML i JS na Onet?
