### ISSUE TITLE
pl.pinterest.com

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#1802]
### Typ elementu
popup
### Link bezpośredni 
`https://pl.pinterest.com/TytanPL/`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Vivaldi 2.0.1309.42
**Bloker:** AdGuard 3.3.8
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Tego nie naprawiamy, strona mocno zamknięta dla niezalogowanych.
