### ISSUE TITLE
##.popmake-overlay.pum-overlay.pum

### ISSUE THREAD

**Issue by krystian3w** [FiltersHeroes/PolishAnnoyanceFilters#1969]
`##.popmake-overlay.pum-overlay.pum`

- html filtering, może coś jeszcze się da
- `:remove()`, czasem usuwanie pop-upa ⚡ zapperem pomaga, to może i ono pomoże.

### Typ elementu/problemu
- [X] Wyskakujące okienko (popup)
- [] Newsletter (nie popup)
- [] Powiadomienie push (nie „zgoda na geolokalizację”)
- [] Scrollujący filmik
- [] Inny element (np. widget „następny artykuł”)
- [] Widżet kontaktowy/informacji zwrotnej
- [] Strzałka
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Błąd
- [x] Pytanie
- [X] Ulepszenie

**Comment by hawkeye116477** [comment]
A co za wolno?

**Comment by hawkeye116477** [comment]
@krystian3w Niektóre w zasadzie pewnie dałoby radę załatwić regułą usuwająca, np #2052, ale ja nie widzę problemu z jakimś miganiem, spowolnienia też brak, a mieliśmy też przystopować z rozdrabnianiem się. Tak więc, powiem tak, jak dodadzą to do uBO Legacy to może wtedy zrobimy jedną regułę z paru, jeżeli nie będzie to powodować problemów.

**Comment by krystian3w** [comment]
W sumie to slidery social też by można przepisać powoli na `:remove()` z `ra.js` / `rc.js`.

Pewnie część nawet już pewnie nie działa lub zrobili wersje nie łapiącą się na stare filtry.

**Comment by krystian3w** [comment]
W sumie zapper od lat przekłamuje, automatycznie doczepia linowy CSS lub `userstyle_API` (`tab.insert.CSS`).
