### ISSUE TITLE
gwiazdy.wp.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [FiltersHeroes/PolishAnnoyanceFilters#214]
![2017-11-25 15_51_32-wp gwiazdy - pikantne zycie gwiazd plotki i skandale](https://user-images.githubusercontent.com/5884000/33231695-e1f59dda-d1f9-11e7-90c4-2ea45e9fe02a.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.111
chrome 62.0.3202.94

**Comment by hawkeye116477** [comment]
@mat41997 WP raczej swojego sklepu nie ma, także uznajemy to jako reklamę, więc na główną listę.

**Comment by mat41997** [comment]
@hawkeye116477 zgłaszałem na główną to @MajkiIT zostawił to tak jak widać. dlatego uznałem że warto to zgłosić tutaj.

**Comment by hawkeye116477** [comment]
@mat41997 No tak nie do końca zostawił, bo dał filtr na wpkoszyk, ale to najwyraźniej chowa tylko te okazje, a ten element został.
