### ISSUE TITLE
histmag.org

### ISSUE THREAD

**Issue by xMaap** [FiltersHeroes/PolishAnnoyanceFilters#2238]
https://histmag.org/Rozrywki-w-czasach-staropolskich-bawic-sie-kazdy-moze-20864/
![2020-06-27 13 09 54 histmag org 492c3f3bc3c5](https://user-images.githubusercontent.com/36385327/85920865-bbd2e100-b877-11ea-908a-4faaf8e0442a.png)

**Comment by krystian3w** [comment]
Duplicate of #2294

**Comment by krystian3w** [comment]
Duplicate of #2294
