### ISSUE TITLE
rankinginternetu.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [FiltersHeroes/PolishAnnoyanceFilters#231]
![2017-12-14 10_52_15-najlepsi dostawcy internetu - ranking 2017 - najlepszy internet mobilny interne](https://user-images.githubusercontent.com/5884000/33986193-2e782fa2-e0bd-11e7-9668-12a1741a88a5.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.12
Nano Defender 13.0
Chrome 63.0.3239.84

**Comment by hawkeye116477** [comment]
@mat41997 To jest reklama UPC, także do @MajkiIT .
