### ISSUE TITLE
medonetmarket.pl

### ISSUE THREAD

**Issue by xMaap** [FiltersHeroes/PolishAnnoyanceFilters#2344]
https://medonetmarket.pl/e-wizyta-u-internisty-homedoctor
![2020-07-11 05 22 07 medonetmarket pl 2931032193a5](https://user-images.githubusercontent.com/36385327/87215416-8c6faa00-c336-11ea-87f8-1480956f1fee.png)

**Comment by krystian3w** [comment]
Strzałki też nie widzisz?
