### ISSUE TITLE
youtube.com (zalogowani mają się lepiej)

### ISSUE THREAD

**Issue by xMaap** [FiltersHeroes/PolishAnnoyanceFilters#2471]
Chyba od dzisiaj co jakiś czas na na Youtube wyskakuje aby się zalogować. Najlepiej chyba co jakiś czas wchodzić w tryb incognito.

![2020-08-21 23 23 56 www youtube com 230b9955ded0](https://user-images.githubusercontent.com/36385327/90936521-a0aec880-e405-11ea-87e6-727d9fc74dcd.png) |
--- |

**Comment by krystian3w** [comment]
@gwarser wymyślił takie coś, może nie rozwala "homepage":
```
youtube.com##+js(json-prune, [].playerResponse.auxiliaryUi.messageRenderers.upsellDialogRenderer)
youtube.com##+js(json-prune, [].response.topbar.desktopTopbarRenderer.interstitial.consentBumpRenderer)
```
