### ISSUE TITLE
tv-trwam.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#2493]
### Typ elementu
scrollujący filmik
### Link bezpośredni 
`https://tv-trwam.pl/program-tv`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Waterfox Classic 56.3
**Bloker:** Nano Adblocker 1.0.0.151
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
@hawkeye116477 mają RODO do akceptacji w dodatku:

![obraz](https://user-images.githubusercontent.com/35370833/92325197-f8297700-f048-11ea-8fd0-63b5dfd7ed3b.png)


Inaczej nie włącza się film spod "oglądaj".

**Comment by krystian3w** [comment]
@hawkeye116477 / @blocker999  wycięcie filmiku psuje funkcjonalność przycisku `oglądaj`.

"Usztywniamy" by się nie przewijał?

**Comment by blocker999** [comment]
Niewiem może warto poczekać aż ktoś zaproponuje coś lepszego

**Comment by krystian3w** [comment]
Ja widzę opcje:
- wycięcia go i tych buttonów, a kto się zgłosi, że mu ich brakuje to w kółko wyjaśniać czemu zniknęły i czemu nie wrócą (może być link do tego zgłoszenia)

- przeniesienia na sam dół, niby film jest pod listą praktycznie nad stopką - minus ludzie nie będą wiedzieć, że trzeba przewijać na sam spód

- na sztywno wyrównać z górną i prawą krawędzią okna (ucierpi wersja mobilna, bo uBO nie wspiera "media queries" i nie będzie go nigdy wspierał).

  - może jakiś spec wymyśli jak film dźwignąć z `flexbox` lub `grid` nad listę i nie popsuć wyglądu na PC/mobilku.

**Comment by krystian3w** [comment]
@AdamWr / @gwarser macie pomysł może jak skryptem wykryć pierwsze wysunięcie, jakby przycisk "oglądaj" nie miał wtedy ingerencji z `eventem`/`setTimeoutem`/`setIntervalem`.
