### ISSUE TITLE
Co dalej z wewnętrznymi albo alleblock?

### ISSUE THREAD

**Issue by blocker999** [FiltersHeroes/PolishAnnoyanceFilters#2507]
**PolishFiltersTeam** nie zamierza kontynuować repo wewnętrznych, dlatego proponuje aby to @gargul2 przejął tę paczkę i ją kontynuował, skoro ma "chrapkę", co Ty na to?

A może ktoś ma inne pomysły, co, jakie?

**Comment by gargul2** [comment]
Nie bardzo, bo nie umiem tych wszystkich elementów i reklam rozróżniać, co jest czym i gdzie się kwalifikuje itp. wy macie lepszą orientację, a ja nie miałem nigdy zielonego pojęcia. A przy okazji to na polskim repo są blokowane reklamy premium a to zdaje się nic innego jak reklamy wewnętrzne? Czyli polskie repo wspiera reklamy wewnętrzne? Przykłady: https://github.com/MajkiIT/polish-ads-filter/issues/17038 + https://github.com/MajkiIT/polish-ads-filter/issues/17039

**Comment by hawkeye116477** [comment]
Pytaj dyrka, a nie nas, on dodaje jak tam mu się podoba, a bywa też, że potem mówi, że to jednak pomyłka i nie powinno tam trafić.

**Comment by krystian3w** [comment]
Niby `Azet12` zaczął, bo też chciał ukrywania pop-upa na Interii, ale niby w wersji jakiej przygotował filtr to ingerował z trybem pisania nowej wiadomości w layoucie `/next/`.

Teoretycznie można próbować to uznać za nieudolną metodę wykrywania blokowania reklam (a nieudolną, bo bez uBO pewnie wskoczy, coś jak paywalle).

**Comment by gargul2** [comment]
> Pytaj dyrka, a nie nas, on dodaje jak tam mu się podoba...

Zacytowaliście 2 pytania, pierwsze to techniczne więc skierowane do każdego, no ale skoro eksperci od kwalifikacji nie posiadają wiedzy czy premium to to samo co rekl. wewnętrzna to widać daleko od was w tej kwestii nie odstaję.

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/discussions/17400 - 🙏 Rozwój/utrzymanie filtrów AlleBlock

https://github.com/MajkiIT/polish-ads-filter/discussions/17373 -🙏 Brak aktualizacji listy Polskie Filtry Wewnętrzne
