### ISSUE TITLE
mojegotowanie.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#2637]
### Typ elementu
prenumerata
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Mozilla Firefox 83
**Bloker:** uBlock Origin 1.31.1b2
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących (niektóre moduły, bez ciasteczek)
### Dodatkowe informacje mogące mieć znaczenie
Jeszcze jedna prenumerata do tego zgłoszenia: https://github.com/FiltersHeroes/PolishAnnoyanceFilters/issues/2632

(by gargul)

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Duplicate of #2632

**Comment by krystian3w** [comment]
Duplicate of #2636
