### ISSUE TITLE
cgm.pl

### ISSUE THREAD

**Issue by xxcriticxx** [FiltersHeroes/PolishAnnoyanceFilters#265]
push push

![capture](https://user-images.githubusercontent.com/15007183/34468379-a624abb8-eed5-11e7-95b6-6c960d641a2f.PNG)

**Comment by hawkeye116477** [comment]
@xxcriticxx U mnie tego nie ma. Jaką masz wersję filtrów?

**Comment by xxcriticxx** [comment]
nieuzywam tych filtrow

**Comment by hawkeye116477** [comment]
@xxcriticxx To po co zgłaszasz w takim razie?

**Comment by xxcriticxx** [comment]
@hawkeye116477 mucho hejtu w nowym roku

**Comment by hawkeye116477** [comment]
@xxcriticxx Może trochę niezbyt dobrze to zabrzmiało, ale to trochę np. tak jakbym ja nie używał nigdy Firefoxa, a zgłosił Mozilli, że zżera za dużo ramu albo że w kółko się wywala przy otwieraniu stron. Jak zgłaszasz, to po prostu miej włączone te filtry.

**Comment by xxcriticxx** [comment]
ok thx
