### ISSUE TITLE
eska.pl | voxfm.pl

### ISSUE THREAD

**Issue by xMaap** [FiltersHeroes/PolishAnnoyanceFilters#2667]
![Zrzut ekranu z 2020-12-22 17-21-05](https://user-images.githubusercontent.com/36385327/102910075-3f156e00-447a-11eb-9101-cfa857229b5a.png) | ![Zrzut ekranu z 2021-03-25 11-31-42](https://user-images.githubusercontent.com/36385327/112459045-b0a4d700-8d5d-11eb-8c92-5a6f90480c70.png)
--- | ---

**Comment by krystian3w** [comment]
Da się gdzieś indziej wybrać region poza używaniem Google?

**Comment by krystian3w** [comment]
Widzę, że pop-up jest powiązany z tym z nagłówka obok logo, trzeba więc robić analizę z pomocą:

* `:watch-attr`
* `:not(:has())`
* skrypletem jak da się wykryć, co ładuje pop-up na "dzień dobry"

**Comment by krystian3w** [comment]
Na razie testujemy to:
```
eska.pl##+js(ra, style, .popupCity[style*="visible"], complete)
eska.pl##.popupCity:not([style])
```

Na wolnych PC pewnie trzeba czekać na aktualizacje uBO 1.32.5+ z nowym parametrem dla `remove-attr`.

AdGuard pewnie nie chce ukrywania pop-upa, to czekamy czy u siebie zaimplementują logikę `complete` czyli jednorazowe wykonanie jak strona będzie w pełni załadowana zamiast w kółko.

**Comment by krystian3w** [comment]
Pop-up zaczął wracać jak strona całkowicie się załadowała.

**Comment by krystian3w** [comment]
https://github.com/FiltersHeroes/PolishAnnoyanceFilters/issues/2776
