### ISSUE TITLE
streambase.pl

### ISSUE THREAD

**Issue by gzenio22** [FiltersHeroes/PolishAnnoyanceFilters#2668]
Coś w liście polskich filtrów elementów irytujących ubija shoutboxa na tej stronie 

Z aktywną listą

![Screenshot_1](https://user-images.githubusercontent.com/21177361/102917543-b4d30700-4485-11eb-9c0a-0eff5ecdf346.png)

Bez

![Screenshot_1](https://user-images.githubusercontent.com/21177361/102917662-e9df5980-4485-11eb-8ea0-265f0a828349.png)

**Comment by blocker999** [comment]
Ja mam poprawnie, może ktoś sprawdzić ?

**Comment by hawkeye116477** [comment]
Chyba sami już naprawili, podmieniając skrypt, bo wcześniej też coś było u mnie nie halo i jakiś skrypt lista blokowała.

**Comment by gzenio22** [comment]
potwierdzam i zamykam
