### ISSUE TITLE
mojanorwegia.pl

### ISSUE THREAD

**Issue by xMaap** [FiltersHeroes/PolishAnnoyanceFilters#2674]
![Zrzut ekranu z 2020-12-31 08-08-09](https://user-images.githubusercontent.com/36385327/103399005-5e2d9300-4b3f-11eb-9e05-83c467c69d73.png)

**Comment by xMaap** [comment]
Coś źle wycięte
https://www.mojanorwegia.pl/zycie-w-norwegii/rok-2020-najcieplejszy-w-historii-norweskich-pomiarow-takich-temperatur-nie-bylo-przez-120-lat-18356.html
![Zrzut ekranu z 2020-12-31 08-09-27](https://user-images.githubusercontent.com/36385327/103399047-89b07d80-4b3f-11eb-948b-ace69227b6e5.png)

**Comment by krystian3w** [comment]
To niby źle wycięta reklama przez @MajkiIT https://github.com/MajkiIT/polish-ads-filter/issues/17902#issuecomment-743791446

niestety pop-upy na krawędzi obu repozytoriów, może odblokować w reklamach i do ręcznego zamykania.

**Comment by krystian3w** [comment]
PS. ja nie mam wersji pop-upa z niebieskim tłem "umów się na wizytę" a taką z blurem i zablokowanym przewijaniem.
