### ISSUE TITLE
Sign Into YouTube - broken search bar?

### ISSUE THREAD

**Issue by xMaap** [FiltersHeroes/PolishAnnoyanceFilters#2676]
The search engine does not work, you cannot enter anything in it. It is best to check in incognito mode.
<p align="right">[Nie działa wyszukiwarka nie można nic w niej wpisać. Najlepiej sprawdzić w trybie incognito.]</p>

**Comment by krystian3w** [comment]
Sprawdź po ręcznej akceptacji cookies:
```
youtube.com#@#body > .opened[opened][style^="z-index"]
youtube.com#@##consent-bump, body > .opened[opened][style^="z-index"], .yt-consent-banner.yt-consent
```

**Comment by xMaap** [comment]
Winny jest Web Annoyances Ultralist chyba przez blokowanie powiadomienia o logowaniu.

**Comment by krystian3w** [comment]
@yourduskquibbles can you use latest idea by `gwarser`  and other users (https://github.com/uBlockOrigin/uAssets/issues/7636 / https://github.com/uBlockOrigin/uAssets/issues/7842):

https://old.reddit.com/r/uBlockOrigin/wiki/solutions#wiki_youtube
