### ISSUE TITLE
bilkom.pl

### ISSUE THREAD

**Issue by xMaap** [FiltersHeroes/PolishAnnoyanceFilters#2814]
![Zrzut ekranu z 2021-05-04 00-35-36](https://user-images.githubusercontent.com/36385327/116941796-b05afe00-ac70-11eb-819c-2d2bd1f40e0a.png)

**Comment by krystian3w** [comment]
U mnie już wycięte: https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/blob/c5907157c7b76510439549afb524eac2ca102079/PAF_pop-ups_supp.txt#L71

https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/blob/32d22b853215197f3c27c3ea1510d975a1f06c0d/PPB/uBO_AG/popupy_suplement.txt#L64

**Comment by krystian3w** [comment]
Duplicate of https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/2129

**Comment by krystian3w** [comment]
U mnie już wycięte (z przynajmniej 10 miesięcy): 

> suplement dla uBO & AG / moduł pop-upy:
>https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/blob/c5907157c7b76510439549afb524eac2ca102079/PAF_pop-ups_supp.txt#L71
>
> plik roboczy dla suplementacji uBO/AG:
>https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/blob/32d22b853215197f3c27c3ea1510d975a1f06c0d/PPB/uBO_AG/popupy_suplement.txt#L64

dodatkowo oczyść listę **reguł** uBO z takich cośków:

```
no-cosmetic-filtering: bilkom.pl true
```

wyłączenie kosmetycznego filtrowania wyklucza wycięcie tego pop-upa. Pod twoje widzimisię nie będziemy próbować z np. `abort-current-inline-script.js` lub średnio bezpiecznym filtrowaniem sieciowym do ubicia ładowania wtyczki pop-upów "`modal-open`".

Jak niestandardowa lista użyła:

* `@@||bilkom.pl^$shide` lub `@@||bilkom.pl^$specifichide`  (opcjonalnie `ehide` / `elemhide`) 
* ` bilkom.pl#@##promopopup, .modal-backdrop`

to spróbuj u jej autorów zgłosić prośbę o likwidacje.

Opcjonalnie można zrobić negacje filtru "sieciowego": `||bilkom.pl^$shide,important` lub `@@||bilkom.pl^$shide,badfilter` (`badfilter` wymaga zachowania składni, `important` powinien nadpisać większość dziwadeł z `$shide` dla tej domeny).

Filtr kosmetyczny `#@#` (dezaktywator) ma gorzej i trzeba by iść na wojnę z listą co widzi zagrożenie w takiej budowie filtra (choćby użycie `:style(visibility: hidden !important;)`).

---

Jak domena jest dodana do wykluczeń HTTPS aplikacji AdGuard (na Windows/macOS/Android) to też nie ma za bardzo opcji wyciąć pop-up, dezaktywacja tam dodanej domeny może popsuć działanie strony np. logowanie (najczęściej wykluczają strony bankowe / portfele "walutowe" / strony rządowe / znane platformy zdrowotne).
