### ISSUE TITLE
volkswagen.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#2849]
### Link bezpośredni 
`https://www.volkswagen.pl/pl/finansowanie-i-ubezpieczenia/Ubezpieczenia.html`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Waterfox Classic 56.5
**Bloker:** uBlock Origin 1.36.2
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
![](https://i.imgur.com/L7NWUnL.png)

Zgłoszenie opublikowane przez użytkownika **blocker**.

**Comment by krystian3w** [comment]
Raczej powinieneś zgłosić to tu: https://github.com/WaterfoxCo/Waterfox/issues

chyba, że @hawkeye116477  wie o co chodzi lub pop-up to atrapa.

**Comment by krystian3w** [comment]
A błędy lepiej opisywać, by nie analizować tego leading page na dwie karty, co trzeba "odblokować".

**Comment by hawkeye116477** [comment]
Ja bym raczej tego nie dodawał do EI. A jak pojawi się nowa wersja WF Classic, to i tak już tego nie będzie.

**Comment by krystian3w** [comment]
Dalej zostaje czy np. generyk ei lub polskie cookies coś psują po zamknięciu - np. rodo do akceptacji.
