### ISSUE TITLE
dmtrade.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#2871]
### Link bezpośredni 
`https://www.dmtrade.pl/p17488,ltc-t204-dvb-t-t2-h-265.html`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 94.0.4606.114
**Bloker:** uBlock Origin 1.38.6
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
![](https://i.imgur.com/sKF8dUL.png)

Zgłoszenie opublikowane przez użytkownika **blocker**.

**Comment by krystian3w** [comment]
Pop-up trudny do reprodukcji - może trzeba weryfikować specjalnie z poziomu Waterfox Classic.
