### ISSUE TITLE
grupa morele.net

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#2872]
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 94.0.4606.114
**Bloker:** uBlock Origin 1.38.6
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
![](https://i.imgur.com/znbMKtA.png)

`https://www.sklep-presto.pl/`
`https://www.digitalo.pl/`

Zgłoszenie opublikowane przez użytkownika **blocker**.

**Comment by krystian3w** [comment]
Psuje się zmiana kodu pocztowego z nagłówka, zalecane olewać lub poprosić AdamaWr o pomoc z zamykaniem wersji nachalnej, o ile nie wycwani się AdGuard z skrypletem `add-to-local-storage`/`set-cookie`/`ag-set-cookie`.
