### ISSUE TITLE
portal.abczdrowie.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#2873]
### Link bezpośredni 
`https://portal.abczdrowie.pl/pani-janina-mialam-kontakt-z-zakazonym-nie-moge-doprosic-sie-o-test`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 96.0.4664.45
**Bloker:** AdGuard 3.6.14
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
![](https://i.imgur.com/Jj8b3Oz.png)

Zgłoszenie opublikowane przez użytkownika **hdh**.

**Comment by krystian3w** [comment]
Proszę przetestować:

`portal.abczdrowie.pl##.exitintent`
