### ISSUE TITLE
player.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#2874]
### Link bezpośredni 
`https://player.pl/programy-online/player-poleca-odcinki,522/odcinek-375,S02E375,224984`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 94.0.4606.114
**Bloker:** uBlock Origin 1.38.6
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
![bad](https://user-images.githubusercontent.com/23176832/142761379-b552217c-a49a-47d8-8299-5db49e2d1676.png)

Zgłoszenie opublikowane przez użytkownika **blocker**.

**Comment by krystian3w** [comment]
Badanie wyskakuje losowo, zapisz stronę do zip?
