### ISSUE TITLE
wronki.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#2888]
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 96.0.4664.97
**Bloker:** uBlock Origin 1.38.6
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
" Gmina Wronki

URZĄD MIASTA I GMINY WRONKI
Czy chciałbyś otrzymywać powiadomienia o najważniejszych wydarzeniach?
Włącz powiadomienia "

Zgłoszenie opublikowane przez użytkownika **blocker**.

**Comment by krystian3w** [comment]
Znaczy wielki push?
