### ISSUE TITLE
sulmierzyce.info

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#2891]
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 96.0.4664.113
**Bloker:** uBlock Origin 1.38.6
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
Coś rozwala stronę.

Zgłoszenie opublikowane przez użytkownika **blocker**.

**Comment by krystian3w** [comment]
Ale jak to nie nasze projekty to nie baw się, że znalazłeś darmową matkę Teresę.

**Comment by hawkeye116477** [comment]
To nasze i co ciekawe, tym razem @krystian3w nabroił => https://github.com/FiltersHeroes/PolishAnnoyanceFilters/commit/d4c675182a2da1e9fe6e8672f504db1bb42108f1 :smile_cat: .
