### ISSUE TITLE
auto-swiat.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#2892]
### Link bezpośredni 
`https://www.przegladsportowy.pl/`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 96.0.4664.110
**Bloker:** AdGuard 3.6.16
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
![](https://i.imgur.com/KS4zBia.png)

Zgłoszenie opublikowane przez użytkownika **zz**.

**Comment by krystian3w** [comment]
To nie jest pop-up (brakuje mu pełnoekranowego tla).

Przy aktywnych modułach trzeba aktywować  ten co się nazywa "inne elementy" / other elements.
