### ISSUE TITLE
atrium-plejada.pl, atrium-mosty.pl, atrium-reduta.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#2893]
### Link bezpośredni 
`https://atrium-plejada.pl/`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 96.0.4664.110
**Bloker:** AdGuard 3.6.16
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
![](https://i.imgur.com/UFxVIYd.png)

Zgłoszenie opublikowane przez użytkownika **zz**.

**Comment by krystian3w** [comment]
`atrium-biala.pl,atrium-ch.pl,atrium-copernicus.pl,atrium-gama.pl,atrium-kasztanowa.pl,atrium-koszalin.pl,atrium-molo.pl,atrium-mosty.pl,atrium-plejada.pl,atrium-reduta.pl,atrium-targowek.pl,warszawa.promenada.com`
