### ISSUE TITLE
dziendobry.tvn.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#2896]
### Link bezpośredni 
`https://dziendobry.tvn.pl/gwiazdy/behawiorysta-na-playerpl-o-czym-jest-serial-kto-w-nim-gra-5540461`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 96.0.4664.110
**Bloker:** AdGuard 3.6.17
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
![](https://i.imgur.com/6BN4KsJ.png)

Zgłoszenie opublikowane przez użytkownika **zz**.

**Comment by krystian3w** [comment]
u mnie działa skryptlet.

**Comment by krystian3w** [comment]
Opcjonalnie można blokować autodtwarzanie i nie przewijać po ręcznym uruchomieniu.

https://github.com/FiltersHeroes/PolishAnnoyanceFilters/wiki/Jak-zablokowa%C4%87-autoodtwarzanie-filmik%C3%B3w%3F
