### ISSUE TITLE
sklepkupiec.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#2898]
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 96.0.4664.113
**Bloker:** uBlock Origin 1.40.4
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
" Witaj!
Zapraszamy do zapisania się do naszego newslettera. "

Zgłoszenie opublikowane przez użytkownika **blocker**.

**Comment by hawkeye116477** [comment]
Dlaczego to https://github.com/FiltersHeroes/PolishAnnoyanceFilters/commit/e74ae9946eaf4aab754021ae7ea4a5d36247c38a zostało usunięte?

**Comment by blocker999** [comment]
sorry za zamieszanie, robie małe noworoczne porządki, jaby co to zaraz przywróce to spowrotem

**Comment by krystian3w** [comment]
W przypadku sklepów i pytań o kod pocztowy w pop-upie to tego nie blokuj prostym filtrem, pop-up powinien wracać na żądanie jak gdzieś mają przycisk "podaj kod pocztowy".

Niestety nie ma gwarancji, że uBo przerwie wyskakiwanie a AdamWr raczej naprawi tylko te z namolnym pop-upem gdzie go nie było jak da się prostym JavaScript na poziomie ich aplikacji.
