### ISSUE TITLE
allegro.pl

### ISSUE THREAD

**Issue by Joduai** [FiltersHeroes/PolishAnnoyanceFilters#2908]
### Typ elementu lub problemu

- [ ] Wyskakujące okienko (popup)
- [ ] Newsletter (nie popup)
- [ ] Powiadomienie push (nie „zgoda na geolokalizację”)
- [ ] Scrollujący filmik
- [ ] Inny element (np. widget „następny artykuł”)
- [ ] Widżet kontaktowy/informacji zwrotnej
- [ ] Strzałka
- [ ] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [ ] Tło zawierające autopromocję
- [ ] Tytuł strony zachęcający do powrotu
- [ ] Reklama prenumeraty/e-wydania gazety
- [X] Błąd
- [ ] Pytanie
- [ ] Ulepszenie

### System operacyjny

Windows

### Przeglądarka internetowa

firefox 96.0.1

### Bloker

uBlock Origin 1.40.8

### Używane listy filtrów

3. Polskie Filtry Elementów Irytujących

Serwus
Po ostatnich zmianach na alegroszu dzisiaj wysiadło wyświetlanie  galerii. 
Wyświetla się biała strona po kliknięciu w foto. 
Wyłączenie "Polskie Filtry Elementów Irytujących" doraźnie rozwiązuje sprawę.
Jest jakiś sposób szybkiej edycji zasubskrybowanego filtra żebym mógł pokombinować który wpis powoduje cały ambaras?

### Zasady pisania

- [X] Zapoznałem się z [netykietą](https://pl.wikipedia.org/wiki/Netykieta)

**Comment by hawkeye116477** [comment]
Nie wiem o co dokładnie chodzi. U mnie wydaje się wszystko ok. Może jakiś zrzut z zaznaczonym problemem?

**Comment by krystian3w** [comment]
Lub po kliknięciu można generować dopuszczenia.

W ABP niby można było na liście odchaczać bez generowania dopuszczeń - uBo tego nie wspiera (ułomnie może badfilter dla sieciówek).

**Comment by Joduai** [comment]
Dziękuję panowie za jasne wyklarowanie jak to ugryźć.
Sprawdziłem jeszcze czy lista nie gryzie się z jakąś dodatkowo przeze mnie subskrybowaną.
Okazuje się że z włączoną Fanboy’s Annoyance (https://easylist.to/) nie wyświetla galerii po kliknięciu.
Dołączam screenshota, ale pokazuje dokładnie to co widać: białość ;]

Próbowałem z dodawaniem wyjąków do reguł w opisany sposób, ale pomimo wielu prób i zezwoleń dla większości rzeczy jakich tylko dało się dodać z poziomu rejestratora nic nie uwidoczniło zdjęć.
Jedyne co widzę, że jest blokowane z easylist dla przykładowego url to
`Filtr allegro.pl##html:style(overflow: auto !important)
Lista filtrów Fanboy’s Annoyance 
Kontekst allegro.pl
Typ dom
Adres URLhttps://allegro.pl/oferta/timberland-skorzane-buty-za-kostke-sznurowane-42-11679306879`

W konsoli developer tools nic szczególnego nie widać po za toną ostrzeżeń, ale po pobieżnym przescrollowaniu żadne nie dotyczą sprawy.

Nie wiem co jeszcze mogę pokombinować aby jakoś "rozgryźć" to że obydwa filtry się gryzą.

![alegroblankscreen](https://user-images.githubusercontent.com/4009106/149800432-24199d3d-9fbb-4228-a7b8-5c3c48954bbd.jpg)

**Comment by krystian3w** [comment]
Jak znasz angielski to możesz wypełnić ich formularz:

https://github.com/easylist/easylist/issues/new

I zaproponować wymianę css na:

`allegro.pl##body[class]:style(overflow-y: auto !important;)`

I porządnie opisz jak się na stronie z ofertą otwiera galerię zdjęć (repozytorium obsługuje Włoch/Włoszka, Niemiec/Niemka, Australijczyk/Nowozelandczyk - pomijam osoby co od lat robią pr i nie mają praw do modyfikacji pliku na żywo).
