### ISSUE TITLE
kilka💯 irytujących pop-upów o poprawnym dodaniu produktu do koszyka

### ISSUE THREAD

**Issue by d21d3q** [FiltersHeroes/PolishAnnoyanceFilters#2909]
### lista domen z unieszkodliwionym pop-upem:

- botland.com.pl
- allegro.pl
- mediaexpert.pl

nowe możesz wklejać do: **[pola odpowiedzi w tym zgłoszeniu](#issuecomment-new "#issuecomment-new")** (o ile nie jesteś na czarnej liście autora tematu lub organizacji zarządzającej tym repozytorium) (link nie działa z dedykowaną aplikacją mobilną)

---

<details><summary> stary opis zgłoszenia </summary>

### Dodatkowe informacje mogące mieć znaczenie

Podczas zakupów na botlandzie, po każdym dodaniu czegokolwiek do koszyka wyskakuje popup, który nie ma wpływu na zawartość koszyka, a irytuje. 

![obraz](https://user-images.githubusercontent.com/490844/151148070-f462bf6b-6ba3-47f9-931f-d6dda7480f98.png)

Reguły do zablokowania pop-upu:
```
botland.com.pl###blockcart-modal, .modal-backdrop
botland.com.pl##.modal-open:style(overflow: auto !important;)
```

</details>

**Comment by krystian3w** [comment]
W sumie to i Allegro ma taki pop-up.
