### ISSUE TITLE
Invalid line

### ISSUE THREAD

**Issue by Alex-302** [FiltersHeroes/PolishAnnoyanceFilters#2910]
### Typ elementu lub problemu

- [ ] Wyskakujące okienko (popup)
- [ ] Newsletter (nie popup)
- [ ] Powiadomienie push (nie „zgoda na geolokalizację”)
- [ ] Scrollujący filmik
- [ ] Inny element (np. widget „następny artykuł”)
- [ ] Widżet kontaktowy/informacji zwrotnej
- [ ] Strzałka
- [ ] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [ ] Tło zawierające autopromocję
- [ ] Tytuł strony zachęcający do powrotu
- [ ] Reklama prenumeraty/e-wydania gazety
- [X] Błąd
- [ ] Pytanie
- [ ] Ulepszenie

### System operacyjny

Windows

### Przeglądarka internetowa

Chrome 97

### Bloker

AdGuard

### Używane listy filtrów

3. Polskie Filtry Elementów Irytujących

### Dodatkowe informacje mogące mieć znaczenie

[f](https://raw.githubusercontent.com/PolishFiltersTeam/PolishAnnoyanceFilters/master/PPB.txt)
Line 1887 - `‘`
![image](https://user-images.githubusercontent.com/8361299/151788605-625649d7-8041-4922-8e91-cc6c3bfb2c3e.png)

### Zasady pisania

- [X] Zapoznałem się z [netykietą](https://pl.wikipedia.org/wiki/Netykieta)

**Comment by hawkeye116477** [comment]
Thanks for report, gremlin got removed :smile:
