### ISSUE TITLE
kioskpolis.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#2931]
### Link bezpośredni 
`https://kioskpolis.pl/`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 99.0.4844.74
**Bloker:** AdGuard 3.6.17
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
![](https://i.imgur.com/KLjVbPI.png)

Zgłoszenie opublikowane przez użytkownika **gha**.

**Comment by krystian3w** [comment]
Mnie pop-up nie atakuje.
