### ISSUE TITLE
twitter.com

### ISSUE THREAD

**Issue by Yhonay** [FiltersHeroes/PolishAnnoyanceFilters#2947]
### Typ elementu lub problemu

- [ ] Wyskakujące okienko (popup)
- [ ] Newsletter (nie popup)
- [ ] Powiadomienie push (nie „zgoda na geolokalizację”)
- [ ] Scrollujący filmik
- [ ] Inny element (np. widget „następny artykuł”)
- [ ] Widżet kontaktowy/informacji zwrotnej
- [ ] Strzałka
- [ ] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [ ] Tło zawierające autopromocję
- [ ] Tytuł strony zachęcający do powrotu
- [ ] Reklama prenumeraty/e-wydania gazety
- [X] Błąd
- [ ] Pytanie
- [ ] Ulepszenie

### System operacyjny

Windows

### Przeglądarka internetowa

Edge 99.0.1150.52

### Bloker

AdGuard 7.9.1

### Używane listy filtrów

1. Polskie Filtry Elementów Irytujących

### Link bezpośredni

```markdown
https://twitter.com/home
```

### Dodatkowe informacje mogące mieć znaczenie

Linijka
```twitter.com,twitter3e4tixl4xyajtrzo62zg5vztmjuricljdp2c5kshju4avyoid.onion#?#div[class^=css-] > div[tabindex="0"] + div[role=group]:has( > div[data-testid])```
z [PPB/uBO_AG/popupy_suplement.txt](https://github.com/FiltersHeroes/PolishAnnoyanceFilters/blob/19d0f0e8bc54db8f89b475441d90573344da3251/PPB/uBO_AG/popupy_suplement.txt) powoduje, że nie można nikogo zablokować bo okienko "Zablokować użytkownika @xxx?" nie wyświetla się.

### Zasady pisania

- [X] Zapoznałem się z [netykietą](https://pl.wikipedia.org/wiki/Netykieta)

**Comment by krystian3w** [comment]
Po 23 możesz próbować wymusić aktualizację.

Niestety AdGuard takie projekty jak nasze aktualizuje 6 razy co 4 godziny i ciężko się wstrzelić w ten cykl.

**Comment by krystian3w** [comment]
Nowa wersja do testowania:

https://github.com/FiltersHeroes/PolishAnnoyanceFilters/commit/8fbdbdd54765bca582c7b2268832d1dac9f832d5

**Comment by Yhonay** [comment]
Przepraszam że się wtrącę, ale co właściwie robią te reguły i jakie elementy mają ukrywać?
