### ISSUE TITLE
pogoda.interia.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#2949]
### Link bezpośredni 
`https://pogoda.interia.pl/`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 100.0.4896.127
**Bloker:** AdGuard 4.0.163
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
![](https://i.imgur.com/j4NWBbc.png)

Zgłoszenie opublikowane przez użytkownika **zg**.

**Comment by krystian3w** [comment]
Czemu zgłoszenia przechodzą z pominięciem labelowania...
