### ISSUE TITLE
pl.aliexpress.com

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#2952]
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 98.0.4758.102
**Bloker:** uBlock Origin 1.42.4
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane przez użytkownika **blocker**.

**Comment by krystian3w** [comment]
Na pewno "web" Push?

**Comment by blocker999** [comment]
![alli](https://user-images.githubusercontent.com/23176832/168339359-04be5e6c-ee77-4a36-a8d5-def3df2ee8b0.png)

**Comment by krystian3w** [comment]
Na mobilkach tego nie ma.
