### ISSUE TITLE
allegro.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#2953]
### Link bezpośredni 
`https://allegro.pl/oferta/lampa-solarna-led-pochodnia-4-szt-11829806614`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 98.0.4758.102
**Bloker:** uBlock Origin 1.42.4
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
![](https://i.imgur.com/PMP0Pn9.png)

takie guano jest na większości ogłoszeń

Zgłoszenie opublikowane przez użytkownika **blocker**.

**Comment by krystian3w** [comment]
Jak storna przeskakuje pomimo ukrycia elementu to ktoś musi wymyślić html filtering lub skryptlet.

**Comment by blocker999** [comment]
w trybie incognito dalej to samo, więc proszę o pomoc

**Comment by krystian3w** [comment]
Upewnij się, że nie otwierasz oferty jako inicjacę trybu incognito - wtedy Chromium może nie zdążyć wykonać filtrowania kosmetycznego nawet z aktywnym "suspend tabs until ready":


https://github.com/gorhill/uBlock/wiki/Dashboard%3A-Filter-lists#suspend-network-activity-until-all-filter-lists-are-loaded

(Dawniej https://github.com/gorhill/uBlock/wiki/Advanced-settings#suspendtabsuntilready).
