### ISSUE TITLE
polskabezgotowkowa.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#2954]
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 102.0.5005.61
**Bloker:** AdGuard 4.0.171
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane przez użytkownika **gz**.

**Comment by krystian3w** [comment]
ja widzę tylko pop-up.
