### ISSUE TITLE
oddslivesport.com

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#2955]
### Link bezpośredni 
`https://oddslivesport.com/pl/`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 102.0.5005.115
**Bloker:** AdGuard 4.0.181
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane przez użytkownika **zg**.

**Comment by krystian3w** [comment]
Nic innego nie widzę, etykiet bot nie przypisał a autor nie użył pola na opis.
