### ISSUE TITLE
syngenta.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#2956]
### Link bezpośredni 
`https://www.syngenta.pl/`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 102.0.5005.115
**Bloker:** AdGuard 4.0.181
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
![](https://i.imgur.com/oqglnkr.png)

Zgłoszenie opublikowane przez użytkownika **zg**.

**Comment by krystian3w** [comment]
Do oceny czy te widgety wycinamy, bo autorowi coś już wicina:

> ![obraz](https://user-images.githubusercontent.com/35370833/173247720-d27bacbc-f7d4-499b-910c-3660c3d332a4.png) |
> --- |

**Comment by krystian3w** [comment]
https://github.com/FiltersHeroes/PolishAnnoyanceFilters/issues/1324

**Comment by blocker999** [comment]
Oczywiście że scrollujące widzety ( buttony ) wycinamy, dlaczego tu miało by być inaczej ?.

**Comment by krystian3w** [comment]
Hawkeye czasem pisał, że wszystkich nie - ale większość z tamtych stron nie ma ich (padały lub w nowym wyglądzie nie mają).

Przykładem może być jak funkcja nie istnieje w drzewie linków a wynik z Google to trochę za późno (ktoś może szukać np. kalkulatora gdzie indziej).
