### ISSUE TITLE
morizon.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#2959]
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 102.0.5005.115
**Bloker:** AdGuard 4.0.181
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
![](https://i.imgur.com/s5GUuHp.png)

Trzeba chwilę poczekać aż się pojawi.

Zgłoszenie opublikowane przez użytkownika **gz**.

**Comment by krystian3w** [comment]
Nic poza pushem nie widzę, jeszcze nie wycinamy grafik do Google Play i App Store - to hawkeye może zamknąć w wolnej chwili.
