### ISSUE TITLE
musictoolz.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#2961]
### Typ elementu

pop-up

(komentarz usunięty manualnie)

### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 103.0.5060.53
**Bloker:** AdGuard 4.0.181
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane przez użytkownika **ga**.

**Comment by krystian3w** [comment]
@hawkeye116477 chyba coś się popsuło z labelami.

Niestety nie widzę nic ciekawego do wycięcia jak nie ukrył tego webmaster na niedzielę ani jawnych uszkodzeń jakich ga nie może opisać.
