### ISSUE TITLE
forbes.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#2962]
### Typ elementu
scrollujący filmik

### Link bezpośredni 
`https://www.forbes.pl/gospodarka/obwod-kaliningradzki-biznes-w-rosyjskiej-enklawie-walczy-o-przetrwanie/rzlwxnl`

`https://www.forbes.pl/diamenty/2022/relacja-z-gali-diamentow-forbesa-wroclaw-2022/3l56zwe`

### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 103.0.5060.53
**Bloker:** AdGuard 4.0.181
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
![](https://i.imgur.com/rfU9ZVz.png)

Zgłoszenie opublikowane przez użytkownika **ga**.

**Comment by krystian3w** [comment]
Ja tego nie mam, być może AdGuard nas jakoś dezaktywuje.

Dodatkowo polecam dezaktywację autoodtwarzania: https://github.com/FiltersHeroes/PolishAnnoyanceFilters/wiki/Jak-zablokowa%C4%87-autoodtwarzanie-filmik%C3%B3w%3F
