### ISSUE TITLE
tysol.pl

### ISSUE THREAD

**Issue by Alex-302** [FiltersHeroes/PolishAnnoyanceFilters#2974]
### Typ elementu lub problemu

- [x] Inny element (np. widget „następny artykuł”)
- [X] Błąd

### System operacyjny

iOS

### Przeglądarka internetowa

Safari

### Bloker

AdGuard for iOS

### Używane listy filtrów

1. EasyList
2. Polskie Filtry Elementów Irytujących

### Link bezpośredni

```markdown
https://www.tysol.pl/a87920-tak-tanczy-lewandowski-nagranie-z-imprezy-barcelony-podbija-siec-wideo
```

### Dodatkowe informacje mogące mieć znaczenie

Original report with screenshot: https://github.com/AdguardTeam/AdguardFilters/issues/125033
Embed tweets are broken. Not reproduced in Chrome

**Comment by krystian3w** [comment]
Maybe needed is exclude bug in generic cookies rules:

https://github.com/FiltersHeroes/PolishAnnoyanceFilters/blob/b6f323ce162a44d9ed38ffddb3d0dbaf38ccdd97/PPB.txt#L6756-L6767

> ...

https://github.com/FiltersHeroes/PolishAnnoyanceFilters/blob/b6f323ce162a44d9ed38ffddb3d0dbaf38ccdd97/PPB.txt#L10831-L10835

➕

https://github.com/FiltersHeroes/PolishAnnoyanceFilters/blob/b6f323ce162a44d9ed38ffddb3d0dbaf38ccdd97/PAF_supp.txt#L38-L45

> ...

https://github.com/FiltersHeroes/PolishAnnoyanceFilters/blob/b6f323ce162a44d9ed38ffddb3d0dbaf38ccdd97/PAF_supp.txt#L981-L982

These need add fix here https://github.com/FiltersHeroes/PolishSocialCookiesFiltersDev/ and create RTM for MajkiIT.

**Comment by krystian3w** [comment]
Bug rule must exist in these files:

https://github.com/FiltersHeroes/PolishAnnoyanceFilters/blob/master/PPB/inne.txt
https://github.com/FiltersHeroes/PolishAnnoyanceFilters/blob/master/PPB/inne_ogolne.txt

---

Rare chance in these files if "if condition" correct exclude iOS:

https://github.com/FiltersHeroes/PolishAnnoyanceFilters/blob/bc2f301a79af58a207b7615a218950823d5be90d/templates/PPB.template#L93-L95


https://github.com/FiltersHeroes/PolishAnnoyanceFilters/blob/master/PPB/uBO_AG/inne_AG.txt
https://github.com/FiltersHeroes/PolishAnnoyanceFilters/blob/master/PPB/uBO_AG/inne_bez_html.txt
https://github.com/FiltersHeroes/PolishAnnoyanceFilters/blob/master/PPB/uBO_AG/inne_html.txt
https://github.com/FiltersHeroes/PolishAnnoyanceFilters/blob/master/PPB/uBO_AG/inne_nie_dla_ff.txt
https://github.com/FiltersHeroes/PolishAnnoyanceFilters/blob/master/PPB/uBO_AG/inne_suplement.txt

**Comment by krystian3w** [comment]
@Alex-302 / @AdamWr works these:

`@@||tysol.pl^$elemhide`

If yes then I can check only cosmetic filters rules and omit network filtering.

**Comment by krystian3w** [comment]
I think someting Safari do not regonize iframes, so inject specific css:

https://github.com/FiltersHeroes/PolishAnnoyanceFilters/blob/75168662f6c476019f4942031894d21deb72cac7/PPB/inne.txt#L915

into iframes.

Twitter have  div with id `#app`.

https://github.com/AdguardTeam/AdguardForiOS/issues - a little too many to found this with iframes.

**Comment by krystian3w** [comment]
https://github.com/FiltersHeroes/PolishAnnoyanceFilters/issues/2974

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdGuardForSafari/issues/105
