### ISSUE TITLE
consent.google.com

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#2976]
### Typ elementu

- [x] Wyskakujące okienko

### Link bezpośredni 
`https://www.google.com`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Mozilla Firefox 103.0.1
**Bloker:** uBlock Origin 1.43
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
4. Wszystkie defaultowe uBO
### Dodatkowe informacje mogące mieć znaczenie
![](https://i.imgur.com/m8UtZDN.png)

Stare filtry jak:
```
google.*##^script:has-text(consentCookiePayload)
google.*##+js(acis, document.cookie, YES+)
google.*##+js(aeld, DOMContentLoaded, CONSENT)
```

nie działają, blokowanie cookies z consent.google.com nie powoduje znikniecia tegoż popupa. Potrzebuje go zlikwidować z wyszukiwarki bo jest niezwykle irytujący jak ktoś czyści ciasteczka z zamknieciem FF.

Zgłoszenie opublikowane przez użytkownika **noname60**.

**Comment by xMaap** [comment]
Proponuje zainstalować rozszerzenie I don't care about cookies.

**Comment by krystian3w** [comment]
Mogę zaktualizować wyszukiwany tekst: "zaakceptuj wszystko".

**Comment by krystian3w** [comment]
Należy za 10 minut wymusić aktualizację polskiej listy:

https://github.com/FiltersHeroes/PolishCookieConsent/blob/master/README.pl.md#jak-zainstalowa%C4%87

**Comment by krystian3w** [comment]
@hawkeye116477 umiesz dobezpieczyć to by nie przeciążać Google:

```javascript
www.google.com,www.google.pl##+js(clickTimeout, [aria-label="Zanim przejdziesz do wyszukiwarki Google"] button + button div)
```
