### ISSUE TITLE
xgp.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#2986]
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 104.0.5112.101
**Bloker:** AdGuard 4.1.1
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
![](https://i.imgur.com/Mmb0cQq.png)

Zgłoszenie opublikowane przez użytkownika **xg**.

**Comment by krystian3w** [comment]
#hpb.hpb

NNW(z)P.

**Comment by krystian3w** [comment]
@hawkeye116477 możesz podwędzić akceptowanie cookies (blokują ramki z YouTube, disqus, Twitterem i inne takie) z commitu AdamaWr.
