### ISSUE TITLE
zakupy.auchan.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#2992]
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 104.0.5112.101
**Bloker:** AdGuard 4.1.1
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
Po kliknięciu 'Zarezerwuj termin dostawy' nie wyskakuje ważna funkcja.
![](https://i.imgur.com/izr0se7.png)

Zgłoszenie opublikowane przez użytkownika **zv**.

**Comment by krystian3w** [comment]
funkca nie istnieje.
