### ISSUE TITLE
national-geographic.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#2994]
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 105.0.5195.52
**Bloker:** AdGuard 4.1.18
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

```adblock
https://www.national-geographic.pl/
https://www.elle.pl/
https://www.glamour.pl/
https://www.kobieta.pl/
https://www.mojegotowanie.pl/
https://www.mojpieknyogrod.pl/
https://www.przyslijprzepis.pl/
```

![](https://i.imgur.com/aTFTGZx.png)

Zgłoszenie opublikowane przez użytkownika **zv**.

**Comment by krystian3w** [comment]
Dodane na wiarę.

**Comment by krystian3w** [comment]
Mam podejrzenie, że to siedzi jakoś w gemius lub stat24 i wtedy przyda się EasyPrivacy?
