### ISSUE TITLE
national-geographic.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#3013]
### Link bezpośredni 
`https://www.national-geographic.pl/traveler/artykul/nordic-walking-jak-zaczac-chodzenie-z-kijkami`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 106.0.5249.119 
**Bloker:** AdGuard 4.1.37
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
![](https://i.imgur.com/gGoCLbu.png)

Zgłoszenie opublikowane przez użytkownika **vh**.

**Comment by krystian3w** [comment]
Mnie chowa się na zawsze lub miga.
