### ISSUE TITLE
hejto.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#3019]
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 107.0.5304.110
**Bloker:** AdGuard 4.1.39
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
![](https://i.imgur.com/9Dhjwor.png)

Zgłoszenie opublikowane przez użytkownika **xgx**.

**Comment by krystian3w** [comment]
Storna nie che by pop-up znikał #3009.

**Comment by blocker999** [comment]
Ja tego niemam
