### ISSUE TITLE
prezydent.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#3020]
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 104.0.5112.81
**Bloker:** uBlock Origin 1.44.2
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane przez użytkownika **blocker**.

**Comment by krystian3w** [comment]
Przydał by się dokładny link.

Część filmów nie przewija się jak blokujemy autodotwrzanie nawet wyciszonego odtwarzacza:

https://github.com/FiltersHeroes/PolishAnnoyanceFilters/wiki/Jak-zablokowa%C4%87-autoodtwarzanie-filmik%C3%B3w%3F

Potem zostaje ocenić czy jest sens używać Comodo Dragon.
