### ISSUE TITLE
hejto.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [FiltersHeroes/PolishAnnoyanceFilters#3021]
### Typ elementu lub problemu

- [ ] Wyskakujące okienko (popup)
- [ ] Newsletter (nie popup)
- [ ] Powiadomienie push (nie „zgoda na geolokalizację”)
- [ ] Scrollujący filmik
- [X] Inny element (np. widget „następny artykuł”)
- [ ] Widżet kontaktowy/informacji zwrotnej
- [ ] Strzałka
- [ ] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [ ] Tło zawierające autopromocję
- [ ] Tytuł strony zachęcający do powrotu
- [ ] Reklama prenumeraty/e-wydania gazety
- [ ] Błąd
- [ ] Pytanie
- [ ] Ulepszenie

### System operacyjny

Linux/Unix

### Przeglądarka internetowa

ff latest

### Bloker

ubo llateest

### Używane listy filtrów

1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących

### Link bezpośredni

```markdown
https://www.hejto.pl/
```

### Dodatkowe informacje mogące mieć znaczenie

Pływająca stopka

### Zasady pisania

- [X] Zapoznałem się z [netykietą](https://pl.wikipedia.org/wiki/Netykieta)

**Comment by krystian3w** [comment]
Nie wycinamy już pływających stopek ani nie usadzamy na sam dół.

**Comment by blocker999** [comment]
Od kiedy scroolujące paski są nieirytujące i od kiedy ich nie usuwamy @hawkeye116477

**Comment by hawkeye116477** [comment]
No już trochę czasu minęło od kiedy zrezygnowaliśmy z zajmowania się częścią scrollujących elementów.
Chociaż ten pasek może jednak by się kwalifkował do schowania, tym bardziej, że to nie jest jakiś ważny stały element.
