### ISSUE TITLE
mastodon - strzałki Font Awesome

### ISSUE THREAD

**Issue by Veticia** [FiltersHeroes/PolishAnnoyanceFilters#3025]
### Typ elementu lub problemu

- [ ] Wyskakujące okienko (popup)
- [ ] Newsletter (nie popup)
- [ ] Powiadomienie push (nie „zgoda na geolokalizację”)
- [ ] Scrollujący filmik
- [ ] Inny element (np. widget „następny artykuł”)
- [ ] Widżet kontaktowy/informacji zwrotnej
- [X] Strzałka
- [ ] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [ ] Tło zawierające autopromocję
- [ ] Tytuł strony zachęcający do powrotu
- [ ] Reklama prenumeraty/e-wydania gazety
- [X] Błąd
- [ ] Pytanie
- [ ] Ulepszenie

### System operacyjny

Windows

### Przeglądarka internetowa

Edge 107.0.1418.56

### Bloker

AdGuard 7.11.3

### Używane listy filtrów

1. Polskie Filtry Elementów Irytujących

### Dodatkowe informacje mogące mieć znaczenie

Filtr:
`~cm-silesia.pl,~gafka.pl,~katowice.pl,pl,~proxima.pl,~wroc.pl##.fa-angle-double-up`
ukrywa strzałki bezkrytycznie w całym pl. Strzałki te są używane min w mastodonie glitch-soc do zwijania postów celem zaoszczędzenia miejsca na ekranie.

### Zasady pisania

- [X] Zapoznałem się z [netykietą](https://pl.wikipedia.org/wiki/Netykieta)

**Comment by krystian3w** [comment]
Mnie też taki filtr denerwuje, raczej skłaniałbym się za jej usunięciem i pochodnych z font awesome.
