### ISSUE TITLE
chopin.polskieradio.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#3037]
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 108.0.5359.98
**Bloker:** AdGuard 4.1.46
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
![](https://i.imgur.com/dEdBR0j.png)

Zgłoszenie opublikowane przez użytkownika **gj**.

**Comment by krystian3w** [comment]
https://github.com/FiltersHeroes/PolishAnnoyanceFilters/commit/38da4e9b48ca616792e3b35c07da789622289340#diff-52918efd5a087287d621357da2fcd3124973ae9982b9c2638cbb20757482559dR194
