### ISSUE TITLE
strimeo.tv

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#3038]
### Link bezpośredni 
`https://www.strimeo.tv/gryfow-slaski-co-w-ramach-funduszu-soleckiego/`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 108.0.5359.124
**Bloker:** AdGuard 4.1.53
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
![](https://i.imgur.com/UQgSXXZ.png)

Zgłoszenie opublikowane przez użytkownika **ch**.

**Comment by krystian3w** [comment]
zgłoszenia zamykaj labelami "zatwierdzone" / "odrzucone"...
