### ISSUE TITLE
elportal.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#3041]
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 108.0.5359.124
**Bloker:** AdGuard 4.1.53
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
![](https://i.imgur.com/oY1L5N6.png)

Zgłoszenie opublikowane przez użytkownika **hvb**.

**Comment by krystian3w** [comment]
Strona trochę przymula przeglądarkę...
