### ISSUE TITLE
dok-oswiata-kadry.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#3049]
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 109.0.5414.119
**Bloker:** AdGuard 4.1.53
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
```
https://dok-oswiata-kadry.pl/
https://poradnik-dyrektora.pl/
https://nadzornadszkola.wip.pl/
https://kwadransdyrektora.wip.pl/ - tutaj jest tylko powiadomienie
https://odo.wip.pl/ - tutaj jest tylko popup
```
![](https://i.imgur.com/JY0gq6V.png)![](https://i.imgur.com/nPBvl2E.png)

Zgłoszenie opublikowane przez użytkownika **vjg**.

**Comment by krystian3w** [comment]
#3049 #3056 #3057
