### ISSUE TITLE
polska-ie.com

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#3063]
### Link bezpośredni 
`https://www.polska-ie.com/`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Mozilla Firefox 111 + Opera 95
**Bloker:** uBlock Origin 1.47.5rc7
**Używane filtry:** 
Polskie Filtry Elementów Irytujących oraz inne listy.
### Dodatkowe informacje mogące mieć znaczenie
[SCREENSHOOT](https://user-images.githubusercontent.com/72945564/227714776-671d0769-b45d-4cec-accc-c338174e2068.png)

Żaba-Monika.

Zgłoszenie opublikowane przez użytkownika **felix-22**.

**Comment by krystian3w** [comment]
Zamykamy labelami.
