### ISSUE TITLE
obserwatorlogistyczny.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#3075]
### Link bezpośredni 
`https://obserwatorlogistyczny.pl/2023/04/26/juz-ponad-750-000-osob-kupilo-niemiecki-bilet-za-49-euro/`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 112.0.5615.165
**Bloker:** AdGuard 4.1.55
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
![](https://i.imgur.com/cvIIIOf.png)

Zgłoszenie opublikowane przez użytkownika **xgc**.

**Comment by krystian3w** [comment]
`pl###check-also-box`

**Comment by krystian3w** [comment]
Mnie to wygląda na błąd w AdGuard 4.1.55.
