### ISSUE TITLE
genialne.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#3089]
### Link bezpośredni 
`https://genialne.pl/hortensja-nie-kwitnie-pomimo-staran-byc-moze-ty-tez-popelniasz-ten-powszechny-blad/`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 113.0.5672.126
**Bloker:** AdGuard 4.1.55
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
![](https://i.imgur.com/RcpIpyp.png)

Zgłoszenie opublikowane przez użytkownika **cvg**.

**Comment by krystian3w** [comment]
v
