### ISSUE TITLE
citroen-shop.eu

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#3094]
### Link bezpośredni 
`https://citroen-shop.eu/pl/`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 114.0.5735.106
**Bloker:** AdGuard 4.1.56
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

Trzeba chwilę poczekać (chyba lata)

![](https://i.imgur.com/NHGhEEB.png)

Zgłoszenie opublikowane przez użytkownika **vcv**.

**Comment by krystian3w** [comment]
@blocker999 / @hawkeye116477 jak dla mnie za małe na pop-up i w rogu.
