### ISSUE TITLE
hejto.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [FiltersHeroes/PolishAnnoyanceFilters#3101]
### Typ elementu lub problemu

- [ ] Wyskakujące okienko (popup)
- [ ] Newsletter (nie popup)
- [ ] Powiadomienie push (nie „zgoda na geolokalizację”)
- [ ] Scrollujący filmik
- [ ] Inny element (np. widget „następny artykuł”)
- [ ] Widżet kontaktowy/informacji zwrotnej
- [ ] Strzałka
- [ ] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [ ] Tło zawierające autopromocję
- [ ] Tytuł strony zachęcający do powrotu
- [ ] Reklama prenumeraty/e-wydania gazety
- [X] Błąd
- [ ] Pytanie
- [ ] Ulepszenie

### System operacyjny

Linux/Unix

### Przeglądarka internetowa

ff 102.0.1

### Bloker

ubo 1.50.0

### Używane listy filtrów

1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
4. 
5. 

### Link bezpośredni

```markdown
https://www.hejto.pl/najnowsze
```

### Zasady pisania

- [X] Zapoznałem się z [netykietą](https://pl.wikipedia.org/wiki/Netykieta)

**Comment by krystian3w** [comment]
> ### Dodatkowe informacje mogące mieć znaczenie
> *No response*

Zabrakło opisu po polsku co jest konkretnie zepsute (do tego służy u nas pole "informacje mogące mieć znaczenie"), bo nie sztuką jest dodać takie 3 filtry i powiedzieć "naprawiłem":

```adb
@@||hejto.pl^$all
@@$all,domain=hejto.pl
@@||hejto.pl^$ehide
hejto.pl#@#+js()
```

pewnie nikt z 3 osób aktualizujące pliki nie odwiedza tego portalu codziennie i z opcją sprawdzania logowania.

**Comment by krystian3w** [comment]
@gwarser tu zawieszało się na `body` z `spoof-css`.
