### ISSUE TITLE
mbank.pl 

### ISSUE THREAD

**Issue by gwarser** [FiltersHeroes/PolishAnnoyanceFilters#3102]
### Typ elementu lub problemu

- [ ] Wyskakujące okienko (popup)
- [ ] Newsletter (nie popup)
- [ ] Powiadomienie push (nie „zgoda na geolokalizację”)
- [ ] Scrollujący filmik
- [x] Inny element (np. widget „następny artykuł”)
- [ ] Widżet kontaktowy/informacji zwrotnej
- [ ] Strzałka
- [ ] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [ ] Tło zawierające autopromocję
- [ ] Tytuł strony zachęcający do powrotu
- [ ] Reklama prenumeraty/e-wydania gazety
- [X] Błąd
- [ ] Pytanie
- [ ] Ulepszenie

### System operacyjny

Linux/Unix

### Przeglądarka internetowa

Nightly 116.0a1 (2023-06-27) (64-bit)

### Bloker

uBO 1.50.1b6

### Używane listy filtrów

1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
4. 
5. 

### Link bezpośredni

```markdown
https://online.mbank.pl/history
```

### Dodatkowe informacje mogące mieć znaczenie

Jak coś wyszukam w historii i najadę kursorem na wynik strona się wywala i pokazuje tylko 

>'get overflow' called on an object that does not implement interface CSS2Properties.

Jedyne filtry to

```
+45	##body, html:style(background-attachment: fixed !important)		online.mbank.pl		get	dom	https://online.mbank.pl/history?operationbalance=off&extendedview=false
+45	##+js(spoof-css, body\, html, background-attachment, unset)		online.mbank.pl		get	scriptlet	https://online.mbank.pl/history?operationbalance=off&extendedview=false
```

więc pewnie wina `spoof-css`.

### Zasady pisania

- [X] Zapoznałem się z [netykietą](https://pl.wikipedia.org/wiki/Netykieta)

**Comment by gwarser** [comment]
Wyłącznie "Polskie Filtry Elementów Irytujących" pomaga.

**Comment by gwarser** [comment]
https://github.com/uBlockOrigin/uBlock-discussions/discussions/467#discussioncomment-6209086 ?

**Comment by krystian3w** [comment]
Dyskusja zbanowana, mogę zawęzić reguły do jednej polskiej strony, zakładam że podobnie buguje się na #3101 ale tam waćpan nie wkleił komendy błędu.

Podobny błąd miałem dzisiaj w dużej polskiej aplikacji B2B.
