### ISSUE TITLE
telepolis.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#3103]
### Link bezpośredni 
`https://www.telepolis.pl/wiadomosci/aplikacje/youtube-reklamy-blokowanie-adblock`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Mozilla Firefox
**Bloker:** uBlock Origin 1.50
**Używane filtry:** 
nieistotne
### Dodatkowe informacje mogące mieć znaczenie
Propozycja, nie błąd. 
Strona prezentuje artykuły w sposób nieskończonego scrollowania. Prośba o zablokowanie tego. Wcześniejsze moje prymitywne rozwiązanie przestało działać, bo coś zmienili. 
Dziękuję.

Zgłoszenie opublikowane przez użytkownika **Jan**.

**Comment by krystian3w** [comment]
Moje chyba też padło, bo jakieś dodawałem pod kilka portali, oznaczę jako potrzebna pomoc.

**Comment by krystian3w** [comment]
```adb
||telepolis.pl/*?scroll=$xmlhttprequest,domain=telepolis.pl
telepolis.pl##.infinite-content-container #spinner.spinner
||telepolis.pl/home/_img/loader.gif$image,domain=www.telepolis.pl
``` 

to wydaje się działać, @gwarser dalej czytasz "telepolię"?

**Comment by gwarser** [comment]
> to wydaje się działać

Działa. Dzięki, też miałem z tym problem i brak czasu, by naprawić :)

**Comment by krystian3w** [comment]
Nowe wyglądają tak: https://github.com/FiltersHeroes/PolishAnnoyanceFilters/commit/f7e410124fd60d43c020b553d94f96082cf2e263

https://github.com/FiltersHeroes/PolishAnnoyanceFilters/blob/f7e410124fd60d43c020b553d94f96082cf2e263/PPB/inne_sieciowe.txt#L33-L34
