### ISSUE TITLE
oiot.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#3107]
### Link bezpośredni 
`https://oiot.pl/sterownik-klima-zaoszczedzi-prad-usprawni-klimatyzacje/`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 114.0.5735.198
**Bloker:** AdGuard 4.1.56
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
Nie wczytują się następne wpisy
![](https://i.imgur.com/TS8rN1z.png)

Zgłoszenie opublikowane przez użytkownika **vg**.

**Comment by krystian3w** [comment]
Bo niektórych denerwują, z pomocą loggera można dezaktywować blokadę ładowania do 5 kolejnych newsów.
