### ISSUE TITLE
orange.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#3108]
### Link bezpośredni 

`https://www.orange.pl/view/kontakt`
`https://www.orange.pl/duze-firmy/pomoc` - wycięcie najważniej treści osadzanej ramką

### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 114.0.5735.198
**Bloker:** AdGuard 4.1.56
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

`orange.pl/view/kontakt`: Nie uruchamia się okno do kontaku oraz czat po kliknięciu po kliknięciu "Zamów rozmowę" oraz "Uruchom"

<details><summary> srceen </summary>

![](https://i.imgur.com/wxfedSZ.png)

</details>

Zgłoszenie opublikowane przez użytkownika **sdc**.

**Comment by krystian3w** [comment]
Czaty irytują, jak wskakują od razu przy pierwszej wizycie, stąd wycięcie.

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/15855

**Comment by xMaap** [comment]
@krystian3w Ten czat chyba już nie wyskakuje po wejściu na stronę. Przynajmniej u mnie nawet sprawdzałem w incognito.

**Comment by krystian3w** [comment]
Ja niestety mam go od drugiej wizyty i niestety różni się tylko tym atrybutuem `style="..."`.
