### ISSUE TITLE
giacomo.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#3111]
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 114.0.5735.198
**Bloker:** AdGuard 4.1.56
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
Trzeba chwilę poczekać
![](https://i.imgur.com/aRmcjJJ.jpg)

Zgłoszenie opublikowane przez użytkownika **zvx**.

**Comment by krystian3w** [comment]
Niby https://github.com/FiltersHeroes/PolishAnnoyanceFilters/blob/996b3d2ec6e539080cfef10fb0797d2eb239ef88/PPB/newslettery_ogolne.txt#L2
