### ISSUE TITLE
benchmark.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#3114]
### Link bezpośredni 
`https://www.benchmark.pl/1/aktualnosci.html`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 114.0.5735.198
**Bloker:** AdGuard 4.1.56
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
![](https://i.imgur.com/20BsrMG.png)

Zgłoszenie opublikowane przez użytkownika **zcz**.

**Comment by krystian3w** [comment]
Na pewno po dezaktywacji listy wracają?
