### ISSUE TITLE
youtube.com

### ISSUE THREAD

**Issue by gzenio22** [FiltersHeroes/PolishAnnoyanceFilters#3120]
### Typ elementu lub problemu

- [ ] Wyskakujące okienko (popup)
- [ ] Newsletter (nie popup)
- [ ] Powiadomienie push (nie „zgoda na geolokalizację”)
- [ ] Scrollujący filmik
- [ ] Inny element (np. widget „następny artykuł”)
- [ ] Widżet kontaktowy/informacji zwrotnej
- [ ] Strzałka
- [ ] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [ ] Tło zawierające autopromocję
- [ ] Tytuł strony zachęcający do powrotu
- [ ] Reklama prenumeraty/e-wydania gazety
- [X] Błąd
- [ ] Pytanie
- [ ] Ulepszenie

### System operacyjny

Windows

### Przeglądarka internetowa

Każda na windows

### Bloker

adguard 7.15.0. Nightly 

### Używane listy filtrów

1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
4. 
5. 

### Link bezpośredni

```markdown
youtube.com
```

### Dodatkowe informacje mogące mieć znaczenie

![Poprawnie wyświetlająca sie strona główna](https://github.com/FiltersHeroes/PolishAnnoyanceFilters/assets/21177361/6b0b3bb0-3534-4e45-8e33-d9c8c0d77f8b)
![Screenshot_1](https://github.com/FiltersHeroes/PolishAnnoyanceFilters/assets/21177361/8e2152d5-bbac-4f52-92e8-accd1349ae8e)

Kiedy w adguardzie mam włączoną liste elementow irytujących strona główna YT wygląda u mnie tak jak na screenie nr 2 gdy ją wyłącze i kilka razy odswierze strone sposob wyswietlania wraca do normy

Na reklame ze screena nie zwracajcie uwagi screen byl robiony przy wyłączonych filtrach zupełnie

### Zasady pisania

- [X] Zapoznałem się z [netykietą](https://pl.wikipedia.org/wiki/Netykieta)

**Comment by krystian3w** [comment]
Możesz spróbować te dwie reguły w AdGuard wyłączyć, u mnie są poprawnie 3-10 wierszy z uBO.
```adb
www.youtube.com#@#:matches-media((min-width: 1500px) and (max-width: 2000px)) [page-subtype="home"] ytd-rich-grid-renderer:style(--ytd-rich-grid-items-per-row: 4 !important)
www.youtube.com#@#ytd-browse[page-subtype="home"] ytd-rich-grid-row, ytd-browse[page-subtype="home"] #contents.ytd-rich-grid-row:style(display:contents !important)
```

**Comment by gzenio22** [comment]
@krystian3w pewnie pamiętasz ze ja zazwyczaj tylko zgłaszam problemy co nie? Nie znam sie na tym co mi piszesz wyzej :P

**Comment by krystian3w** [comment]
No to jutro po 12 możesz wymusić aktualizację listy i zobaczyć czy AdGuard poprawnie zrozumie wyłączenie przetwarzania reguł kompatybilnych tylko z uBo.

**Comment by gzenio22** [comment]
kurna ale fajnie ze w koncu doszlismy do tego co nie gra ja kilka miesiecy temu tez tutaj zgłaszalem ze cos nie gra to wtedy sie nie dogadalismy Xd

**Comment by krystian3w** [comment]
Nie pamiętam co zgłaszałeś a regułę do miniaturek mamy, by nie było luki w pierwszym wierszu np. 3 kafelki zamiast 4.

**Comment by gzenio22** [comment]
O panie jak ten czas szybko leci :D

**Comment by krystian3w** [comment]
https://github.com/FiltersHeroes/PolishAnnoyanceFilters/issues/3120
https://github.com/AdguardTeam/AdguardFilters/issues/159074
