### ISSUE TITLE
tv-iptv.bid

### ISSUE THREAD

**Issue by gzenio22** [FiltersHeroes/PolishAnnoyanceFilters#3122]
### Typ elementu lub problemu

- [ ] Wyskakujące okienko (popup)
- [ ] Newsletter (nie popup)
- [ ] Powiadomienie push (nie „zgoda na geolokalizację”)
- [ ] Scrollujący filmik
- [ ] Inny element (np. widget „następny artykuł”)
- [x] Widżet kontaktowy/informacji zwrotnej
- [ ] Strzałka
- [ ] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [ ] Tło zawierające autopromocję
- [ ] Tytuł strony zachęcający do powrotu
- [ ] Reklama prenumeraty/e-wydania gazety
- [X] Błąd
- [ ] Pytanie
- [ ] Ulepszenie

### System operacyjny

Windows

### Przeglądarka internetowa

Chrome

### Bloker

Adguard

### Używane listy filtrów

1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
4. 
5. 

### Link bezpośredni

```markdown
https://tv-iptv.bid/
```

### Dodatkowe informacje mogące mieć znaczenie

Okno czatu nie ładuje sie prawdopodobnie odpowiada za to coś z waszej listy @krystian3w żucisz gałką na to? :D 
![Adguard off](https://github.com/FiltersHeroes/PolishAnnoyanceFilters/assets/21177361/da693cd8-7496-4d8d-8f53-b5780c7d4d50)
![Screenshot_1](https://github.com/FiltersHeroes/PolishAnnoyanceFilters/assets/21177361/20f299c8-cd11-4fce-9869-f7d35ef00c3d)

### Zasady pisania

- [X] Zapoznałem się z [netykietą](https://pl.wikipedia.org/wiki/Netykieta)

**Comment by krystian3w** [comment]
Jakiś stary filtr sieciowy blokuje to globalnie, pewnie od jutra po 12 🕛  będzie już działać.
