### ISSUE TITLE
pogoda.interia.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#3134]
### Link bezpośredni 
`https://pogoda.interia.pl/prognoza-dlugoterminowa-warszawa,cId,36917`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome Wersja 118.0.5993.70 (Oficjalna wersja) (64-bitowa)
**Bloker:** uBlock Origin uBlock Origin: 1.52.2
**Używane filtry:** 

1. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
![](https://i.imgur.com/i1erEoC.png)

brakuje fragmentu strony które nie jest reklamą

Zgłoszenie opublikowane przez użytkownika **maciek**.

**Comment by krystian3w** [comment]
Znowu winny jest prekursor listy @blocker999, dodając `pl##.top`.
