### ISSUE TITLE
rmf24.pl

### ISSUE THREAD

**Issue by antek821** [FiltersHeroes/PolishAnnoyanceFilters#3135]
### Typ elementu lub problemu

- [ ] Wyskakujące okienko (popup)
- [ ] Newsletter (nie popup)
- [ ] Powiadomienie push (nie „zgoda na geolokalizację”)
- [ ] Scrollujący filmik
- [ ] Inny element (np. widget „następny artykuł”)
- [ ] Widżet kontaktowy/informacji zwrotnej
- [ ] Strzałka
- [ ] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [ ] Tło zawierające autopromocję
- [ ] Tytuł strony zachęcający do powrotu
- [ ] Reklama prenumeraty/e-wydania gazety
- [X] Błąd
- [ ] Pytanie
- [ ] Ulepszenie

### System operacyjny

Windows

### Przeglądarka internetowa

Edge, Chrome, Vivaldi

### Bloker

Adguard for Windows - 7.15, Adguard for Android 4.1

### Używane listy filtrów

1. Polskie Filtry Elementów Irytujących

Testowo wyłączyłem wszystkie inne listy. Problem występuje tylko i wyłącznie wtedy, gdy włączę Polskie Filtry Elementów Irytujących

### Link bezpośredni

```markdown
https://www.rmf24.pl
```

### Dodatkowe informacje mogące mieć znaczenie

Strona w ogóle się nie pokazuje - widać tylko białe tło. Testowane na 2 różnych telefonach i na komputerze - przeglądarki Chrome, Edge, Vivaldi.

### Zasady pisania

- [X] Zapoznałem się z [netykietą](https://pl.wikipedia.org/wiki/Netykieta)

**Comment by endrjux** [comment]
Wygląda na to, że dodanie `pl###top` w [3f0502a](https://github.com/FiltersHeroes/PolishAnnoyanceFilters/commit/3f0502aeedcf6e945ce29a348f9f3d3e762adeff#diff-583b0eca3bb7c6d26db0b8d5739700c319ffa796fb6d3e5e83c6343b8aadfb10R1075) powoduje ten problem. Bez tego filtru jest ok.

**Comment by krystian3w** [comment]
Winny jest prekursor listy @blocker999.
