### ISSUE TITLE
drtusz.pl

### ISSUE THREAD

**Issue by gwarser** [FiltersHeroes/PolishAnnoyanceFilters#3136]
### Typ elementu lub problemu

- [ ] Wyskakujące okienko (popup)
- [x] Newsletter (nie popup)
- [ ] Powiadomienie push (nie „zgoda na geolokalizację”)
- [ ] Scrollujący filmik
- [ ] Inny element (np. widget „następny artykuł”)
- [ ] Widżet kontaktowy/informacji zwrotnej
- [ ] Strzałka
- [ ] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [ ] Tło zawierające autopromocję
- [ ] Tytuł strony zachęcający do powrotu
- [ ] Reklama prenumeraty/e-wydania gazety
- [X] Błąd
- [ ] Pytanie
- [ ] Ulepszenie

### System operacyjny

Linux/Unix

### Przeglądarka internetowa

Nightly

### Bloker

1.53.5rc10

### Używane listy filtrów

1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących

### Link bezpośredni

```markdown
https://www.drtusz.pl/tusze-do-drukarek-brother-zamienniki-oryginalne-c-50400000003.html
```

### Dodatkowe informacje mogące mieć znaczenie

`drtusz.pl##div.infoBoxHeading:nth-of-type(5), .smallText` ukrywa listę produktów

### Zasady pisania

- [X] Zapoznałem się z [netykietą](https://pl.wikipedia.org/wiki/Netykieta)

**Comment by krystian3w** [comment]
To twórca PPB zrobił:

https://github.com/FiltersHeroes/PolishAnnoyanceFilters/commit/ef928c266d35b149056b5af310647935a56bdfdc

Chyba czas na emeryturę.
