### ISSUE TITLE
stv.info

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#3137]
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 117.0.5938.150
**Bloker:** uBlock Origin 1.53.0
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane przez użytkownika **blocker**.

**Comment by krystian3w** [comment]
Sprawdź z [AutoplayStopper](https://chrome.google.com/webstore/detail/autoplaystopper/ejddcgojdblidajhngkogefpkknnebdh)em:

https://chrome.google.com/webstore/detail/autoplaystopper/ejddcgojdblidajhngkogefpkknnebdh

**Comment by blocker999** [comment]
![STV](https://github.com/FiltersHeroes/PolishAnnoyanceFilters/assets/23176832/2f30f185-faba-412b-a8b1-e1e3478a6e30)

**Comment by krystian3w** [comment]
Powiedziałbym, że jest wymagane do czerwca 2024, jak w lipcu nie będzie w MV3 lub zniknie ze sklepu to stanie się opcjonalne.
