### ISSUE TITLE
sport.interia.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#3139]
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 119.0.6045.159
**Bloker:** AdGuard 4.2.226
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
![](https://i.imgur.com/RuJkjS0.png)

Zgłoszenie opublikowane przez użytkownika **xzz**.

**Comment by krystian3w** [comment]
U mnie działa, @AdamWr problem w silniku 4.2.x?

**Comment by AdamWr** [comment]
Naprawione, dziękuję za zgłoszenie.
