### ISSUE TITLE
instalki.pl

### ISSUE THREAD

**Issue by Alex-302** [FiltersHeroes/PolishAnnoyanceFilters#3144]
### Typ elementu lub problemu

- [ ] Wyskakujące okienko (popup)
- [ ] Newsletter (nie popup)
- [ ] Powiadomienie push (nie „zgoda na geolokalizację”)
- [ ] Scrollujący filmik
- [x] Inny element (np. widget „następny artykuł”)
- [ ] Widżet kontaktowy/informacji zwrotnej
- [ ] Strzałka
- [ ] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [ ] Tło zawierające autopromocję
- [ ] Tytuł strony zachęcający do powrotu
- [ ] Reklama prenumeraty/e-wydania gazety
- [X] Błąd
- [ ] Pytanie
- [ ] Ulepszenie

### System operacyjny

Windows

### Przeglądarka internetowa

Chrome 120

### Bloker

AdGuard

### Używane listy filtrów

1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
4. 
5. 

### Inne rozszerzenia

-

### Dodatkowe informacje mogące mieć znaczenie

Error - two closing `}`
`www.instalki.pl##@media (max-width: 500px) { .post-categories, .post-categories li { background: none !important; padding: 0; margin: 3px -5px; display: inline-flex } }`
https://github.com/FiltersHeroes/PolishAnnoyanceFilters/blob/4864a9475ec1b24867e27b74a9e793392cede388/PAF_other_elements_supp.txt#L216

### Zasady pisania

- [X] Zapoznałem się z [netykietą](https://pl.wikipedia.org/wiki/Netykieta)

**Comment by krystian3w** [comment]
So media cannot by closed like on CSS 3?

```css
@media (max-width: 500px) {
	.post-categories,
	.post-categories li {
		background: none !important;
		padding: 0;
		margin: 3px -5px;
		display: inline-flex
	}
}

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/FiltersRegistry/commit/052c0d13d2398f922be9720476658357d4eb0558#diff-5c46e3602a53f570a5968bc147df526909f3fc61a6ece42c79a31c246cd9b729L2031

**Comment by Alex-302** [comment]
> So media cannot by closed like on CSS 3?

Hm, I didn't realize there was more than one selector.

**Comment by krystian3w** [comment]
As long commas will be not deprecated in raw CSS rules with customized sheet.
