### ISSUE TITLE
mbank.pl

### ISSUE THREAD

**Issue by antek821** [FiltersHeroes/PolishAnnoyanceFilters#3145]
### Typ elementu lub problemu

- [ ] Wyskakujące okienko (popup)
- [ ] Newsletter (nie popup)
- [ ] Powiadomienie push (nie „zgoda na geolokalizację”)
- [x] Scrollujący filmik
- [x] Inny element (np. widget „następny artykuł”)
- [ ] Widżet kontaktowy/informacji zwrotnej
- [ ] Strzałka
- [ ] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [ ] Tło zawierające autopromocję
- [ ] Tytuł strony zachęcający do powrotu
- [ ] Reklama prenumeraty/e-wydania gazety
- [X] Błąd
- [ ] Pytanie
- [ ] Ulepszenie

### System operacyjny

Windows

### Przeglądarka internetowa

Vivaldi (chromium)

### Bloker

Adguard for Windows - 7.16.0

### Używane listy filtrów

1. AdGuard Base
2. I don't care about cookies
3. Fanboy's Annoyances
4. EasyPrivacy
5. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
6. Polskie filtry elementów irytujących
7. Polskie filtry społecznościowe
8. EasyList Polish
9. Polish Anti-Annoying Special Supplement

### Link bezpośredni

```markdown
https://www.mbank.pl
```

### Dodatkowe informacje mogące mieć znaczenie

Polskie filtry elementów irytujących powodują że strona mbanku w ogóle się nie ładuje. Winna jest prawdopodobnie reguła:
```
://*.*$domain=~0.0.0.0|~127.0.0.1|~[::1]|~[::]|~local|~localhost|~stooq.com|~stooq.pl,permissions=autoplay=()
```

### Zasady pisania

- [X] Zapoznałem się z [netykietą](https://pl.wikipedia.org/wiki/Netykieta)

**Comment by krystian3w** [comment]
AdGuard pewnie wykryje zmianę po 10:07.
