### ISSUE TITLE
Brak możliwości dodawania filmów na YT do playlisty

### ISSUE THREAD

**Issue by PiotrSobiegraj** [FiltersHeroes/PolishAnnoyanceFilters#3148]
### Typ elementu lub problemu

- [ ] Wyskakujące okienko (popup)
- [ ] Newsletter (nie popup)
- [ ] Powiadomienie push (nie „zgoda na geolokalizację”)
- [ ] Scrollujący filmik
- [x] Inny element (np. widget „następny artykuł”)
- [ ] Widżet kontaktowy/informacji zwrotnej
- [ ] Strzałka
- [ ] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [ ] Tło zawierające autopromocję
- [ ] Tytuł strony zachęcający do powrotu
- [ ] Reklama prenumeraty/e-wydania gazety
- [X] Błąd
- [x] Pytanie
- [ ] Ulepszenie

### System operacyjny

Windows

### Przeglądarka internetowa

Firefox: 122

### Bloker

uBlock Origin: 1.55.0

### Używane listy filtrów

1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
4. 
5. 

### Link bezpośredni

```markdown
https://www.youtube.com/watch?v=Q86R-d014PQ oraz inne filmy na YT
```

### Dodatkowe informacje mogące mieć znaczenie

Z włączoną Waszą listą przycisk save nia działa.
Z tego co udało mi się ustalić jest związane z tą linijką
`youtube.com#?#ytd-popup-container tp-yt-paper-dialog:-abp-has(yt-touch-feedback-shape)`
co zgodnie z sekcją How to test filters z https://www.reddit.com/r/uBlockOrigin/wiki/solutions/ można zobaczyć na poniższym obrazku.
Po wyłączeniu Waszej listy przycisk działa normalnie. Jak rozumiem ta linijka miała zablokować popupa przycisku Thanks, ale teraz chyba robi więcej szkody niż pożytku...

Czy da sie tę linijkę jakoś whitelistować w uBO?

<img width="947" alt="2024-02-09_03-39" src="https://github.com/FiltersHeroes/PolishAnnoyanceFilters/assets/1130719/46280e74-c8e2-4c3f-9d35-03e98945451c">

### Zasady pisania

- [X] Zapoznałem się z [netykietą](https://pl.wikipedia.org/wiki/Netykieta)

**Comment by krystian3w** [comment]
Tam wskakuje też "pop-up" o subskrypcji premium kanału.
