### ISSUE TITLE
zycierolnika.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#3170]
### Link bezpośredni 
`https://zycierolnika.pl/`
### Moja konfiguracja 
**System operacyjny:** Linux
**Przeglądarka internetowa:** Mozilla Firefox 124.0
**Bloker:** uBlock Origin 1.57.2
**Używane filtry:** 
1. EasyList
2. EasyList - Cookie Notices.
3. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
4. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane przez użytkownika **Example**.

**Comment by krystian3w** [comment]
Niby:

`zycierolnika.pl##.newsletter`

A uprościć pod cały Internet trzeba od nowa.
