### ISSUE TITLE
sportowefakty.wp.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#3179]
### Link bezpośredni 
`https://sportowefakty.wp.pl/boks-zawodowy/1124275/brutalny-nokaut-polak-wypadl-z-ringu`
### Moja konfiguracja 
**System operacyjny:** Linux
**Przeglądarka internetowa:** Mozilla Firefox 124.0
**Bloker:** uBlock Origin 1.57.2
**Używane filtry:** 
1. EasyList
2. EasyList - Cookie Notices.
3. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
4. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane przez użytkownika **Example**.

**Comment by krystian3w** [comment]
Ja nie mam, sugeruję aktualizację uBo do 1.58.0, może zniknie.
