### ISSUE TITLE
spidersweb.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#3183]
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 126.0.6478.126
**Bloker:** AdGuard 4.3.53
**Używane filtry:** 
1. EasyList
2. EasyList - Cookie Notices.
3. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
4. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
![](https://i.imgur.com/34KZxeq.png)

Zgłoszenie opublikowane przez użytkownika **gzg**.

**Comment by krystian3w** [comment]
Cały/całe rok/dziesięciolecia pewnie nie będą rozdawać.
