### ISSUE TITLE
zabka.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#3186]
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 126.0.6478.182
**Bloker:** AdGuard 4.3.53
**Używane filtry:** 
1. EasyList
2. EasyList - Cookie Notices.
3. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
4. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
```
https://www.zabka.pl/
```
Nie działa przewijanie strony

`https://woshwosh.zabka.pl/checkout/`

Nie działa opcja "Do kosza"

Zgłoszenie opublikowane przez użytkownika **sdz**.

**Comment by krystian3w** [comment]
Powinno się naprawić do czwartku (ograniczenia na serwerze AdGuard), dla MV3 dopiero od nowej wersji dodatku dla Chrome w MV3 (na razie nie udostępniają aktualizacji list na rzadanie np. w czwartek).
