### ISSUE TITLE
asta-net.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#3188]
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 127.0.6533.72
**Bloker:** AdGuard 4.3.53
**Używane filtry:** 
1. EasyList
2. EasyList - Cookie Notices.
3. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
4. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
Nie działa przewijanie strony

Zgłoszenie opublikowane przez użytkownika **csz**.

**Comment by krystian3w** [comment]
Wygląda na Pop-up źle dodany przez Blockera - feedbackowy.
