### ISSUE TITLE
airalo.com

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#3190]
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 127.0.6533.88
**Bloker:** AdGuard 4.3.53
**Używane filtry:** 
1. EasyList
2. EasyList - Cookie Notices.
3. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
4. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
![](https://i.imgur.com/c25S6DF.png)

Zgłoszenie opublikowane przez użytkownika **xzs**.

**Comment by krystian3w** [comment]
Ten pan zepsuł https://github.com/FiltersHeroes/PolishAnnoyanceFilters/commit/a847533c204cd1d2378954cce12f971ed181d9d8

Chyba czas wdrożyć, że commity są sprawdzane na wersji dev i publikowane na roboczym przez bota.

**Comment by krystian3w** [comment]
Do czwartku się naprawić powinno bez wymuszania aktualizacji w aplikacji i rozszerzeniach MV2.

W MV3 będzie trzeba czekać na nową wersję dodatku (AdGuard nie planuje jeszcze aktualizacji na żądanie).
