### ISSUE TITLE
ludzie.fakt.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#3194]
### Link bezpośredni 
`https://ludzie.fakt.pl/nie-zyje-znany-youtuber-35-latek-osierocil-dwojke-malych-dzieci/nqmgr2m`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Brave Browser v1.68.137 
**Bloker:** uBlock Origin 1.59.0
**Używane filtry:** 
1. EasyList
2. EasyList - Cookie Notices.
3. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
4. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane przez użytkownika **ToTylkoJa**.

**Comment by krystian3w** [comment]
Nie mamy w ekipie specjalisty do napisania skryptletu przerywającego auto ostrzeżenie.

Rozważ aktywację tego w Brave lub przy pomocy AutoplayStopper:

https://chrome.google.com/webstore/detail/autoplaystopper/ejddcgojdblidajhngkogefpkknnebdh

**Comment by krystian3w** [comment]
W Firefox nie przrwija się, więc pewnie trzeba rozważyć reinstalację uBo, gdy Chromium ma identyczny kod strony fakt.
