### ISSUE TITLE
twojapogoda.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/PolishAnnoyanceFilters#3197]
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 128.0.6613.119
**Bloker:** AdGuard 4.4.22
**Używane filtry:** 
1. EasyList
2. EasyList - Cookie Notices.
3. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
4. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
https://www.twojapogoda.pl/
![](https://i.imgur.com/soepTJe.png)
![](https://i.imgur.com/YMxmEUH.png)
https://www.twojapogoda.pl/wiadomosci/
https://www.twojapogoda.pl/zdjecia/
https://www.twojapogoda.pl/filmy/
![](https://i.imgur.com/gQIKk0l.png)

Zgłoszenie opublikowane przez użytkownika **zxdf**.

**Comment by krystian3w** [comment]
https://github.com/FiltersHeroes/PolishAnnoyanceFilters/commit/ce905a66b68653cce2c3d894f1bf40c5ab0f407a - co autor miał na myśli to nie mam pojęcia.
