### ISSUE TITLE
player.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [FiltersHeroes/PolishAnnoyanceFilters#361]
![2018-02-01-seriale i filmy online na zyczenie kanaly tv - wejdz i ogladaj na player pl](https://user-images.githubusercontent.com/5884000/35659819-b5036278-0708-11e8-970a-8e473bb02ff8.png)

popup

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.28
Nano Defender 13.28
Chrome 64.0.3282.119

</details>

**Comment by blocker999** [comment]
@KonoromiHimaries Niemam

@hawkeye116477 zajrzysz

**Comment by hawkeye116477** [comment]
Też tego nie mam.

**Comment by blocker999** [comment]
@KonoromiHimaries co robimy ?

**Comment by Ravizz** [comment]
Też tego nie mam.
