### ISSUE TITLE
mgsm.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [FiltersHeroes/PolishAnnoyanceFilters#552]
![2018-03-14-asus zenfone max plus zb570tl zenfone max plus m1 x018d dane techniczne telefon](https://user-images.githubusercontent.com/5884000/37399215-5a9ab798-2781-11e8-93a4-6ec988a238d3.png)
`http://www.mgsm.pl/pl/katalog/asus/zenfonemaxpluszb570tl/Asus-Zenfone-Max-Plus-ZB570TL.html`

widżet "kup: asus" do usadzenia

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.34
Nano Defender 13.41
Chrome 65.0.3325.146

</details>

**Comment by blocker999** [comment]
@hawkeye116477 co z tym?

**Comment by hawkeye116477** [comment]
Odrzucamy, nie będziemy się bawić w usadzanie.
