### ISSUE TITLE
cryptoacademy.club

### ISSUE THREAD

**Issue by KonoromiHimaries** [FiltersHeroes/PolishAnnoyanceFilters#572]
![2018-03-17-najswiezsza wiedza o kryptowalutach - cryptoacademy club](https://user-images.githubusercontent.com/5884000/37554328-21284f18-29d7-11e8-9b63-8d5a93df5b1e.png)

widget po prawej do usadzenia + click w artykule do odblokowania

**Comment by hawkeye116477** [comment]
Widget raczej schowamy :smile:.
