### ISSUE TITLE
obrazek kapcia

### ISSUE THREAD

**Issue by blocker999** [FiltersHeroes/PolishAnnoyanceFilters#60]
@hawkeye116477 Co zrobić z tym logiem, proponuje dodać `pl##.grecaptcha-badge` by usunąć to irytujący element, który jest np tu : https://ogryzek.pl/oferta/uslugi-slusarskie-bramy-furtki-ogrodzenia-produkcja-i-montaz-19875.html

![recaptacha](https://user-images.githubusercontent.com/23176832/29170437-e8b48c96-7dd8-11e7-80b5-2b6632044e03.png)

**Comment by hawkeye116477** [comment]
@blocker999 Ok. Można chyba też nieco krócej: `pl###recaptcha`, z tym, że nie wiem czy moja reguła nie zablokuje możliwości wysyłania zapytań. A konta tam nie posiadam niestety.

**Comment by blocker999** [comment]
@hawkeye116477 OK, potestuje to , by to nic nieuszkodziło, ale generalnie jesteś na tak?

**Comment by hawkeye116477** [comment]
@blocker999 Tak
