### ISSUE TITLE
gorzowianin.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [FiltersHeroes/PolishAnnoyanceFilters#604]
![2018-03-24-gorzowianin com - najprawdopodobniej najlepszy portal w miescie](https://user-images.githubusercontent.com/5884000/37868109-efec3100-2fa1-11e8-92f0-8f2eeb516c69.png)

resztki po popupie

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/80eb960ea3acab0a5135e233353cc87b

 uBO 1.15.18
 ND 13.47
 Chr 65.0.3325.181
</details>

**Comment by hawkeye116477** [comment]
To jest reklama zewnętrzna, a więc do @MajkiIT.
