### ISSUE TITLE
moneyguru.com.pl

### ISSUE THREAD

**Issue by blocker999** [FiltersHeroes/PolishAnnoyanceFilters#61]
@hawkeye116477 Pod tym adresem https://www.moneyguru.com.pl/wez-pozyczke/ jest luka na stronie i niejest to wina przeglodarki ani żadnego blockera gdyż pojawia się to na różnych przeglądarkach bez blockera, więc czy coś z tym zrobić?

![moneyguru](https://user-images.githubusercontent.com/23176832/29170994-2fd91888-7ddb-11e7-8ec8-f4b7ed9897e8.png)

**Comment by hawkeye116477** [comment]
@blocker999 Tak, zgłosić do admina strony, niech weźmie się do roboty i naprawia, nie będziemy po nim sprzątać :smiley:. No chyba, że Flash jest potrzebny i dlatego tam nic nie mamy.

**Comment by blocker999** [comment]
@hawkeye116477 OK, zostawie to
