### ISSUE TITLE
ototorun.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [FiltersHeroes/PolishAnnoyanceFilters#625]
![2018-04-03-torun o tym sie mowi w toruniu - ototorun pl](https://user-images.githubusercontent.com/5884000/38229801-b3845b64-370a-11e8-9a9c-90f52d62deba.png)

duży pusty baner

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/80eb960ea3acab0a5135e233353cc87b

 uBO 1.15.18
 ND 13.49
 Chr 65.0.3325.181
</details>

**Comment by krystian3w** [comment]
`###__cmcmedia_upid_26`

**Comment by hawkeye116477** [comment]
To jest reklama, a więc do @MajkiIT .

**Comment by krystian3w** [comment]
Odblokowałem, ale wpuściłem kupę badziewia:

```
ototorun.pl#@#[id*="cmcmedia_upid_"]
@@||bbcdn-static.bbelements.com^$script,domain=cdn.gallery
ototorun.pl#@#A[target="_blank"] > IMG
pl#@##top-reklama
@@||go.eu.bbelements.com^$xmlhttprequest,domain=cdn.gallery
||go.eu.bbelements.com/please/*$script,domain=cdn.gallery
@@||bbcdn-bbnaut.ibillboard.com^$script,domain=cdn.gallery
@@||bbnaut.ibillboard.com/initidmatch?force=1$script,domain=cdn.gallery
@@||bbnaut.ibillboard.com/g/njs/*$script,domain=cdn.gallery
@@||pagead2.googlesyndication.com/pagead/show_ads.js$script,domain=cdn.gallery
@@||mr1a.exs.pl/embed5.php$script,domain=ototorun.pl
@@||mr1-1a.exs.pl/frame71.php$subdocument,domain=ototorun.pl
```

Może komuś przeszkadzało, że wyje.
