### ISSUE TITLE
darmoweogłoszenia.pl

### ISSUE THREAD

**Issue by gomoku** [FiltersHeroes/PolishAnnoyanceFilters#78]
Z jakichś powodów, filtr `pl###sidebar-boxes` znajdujacy się na liście nie przynosi efeku, bo i tak po paru(nastu) sekundach wyskakuje ten upierdliwy baner po prawej stronie. Co dziwne, filtry:

~~`.pl###sidebar-boxes`~~
`www.darmoweogłoszenia.pl###sidebar-boxes` 
`www.xn--darmoweogoszenia-ryc.pl###sidebar-boxes `
`darmoweogłoszenia.pl###sidebar-boxes `
`xn--darmoweogoszenia-ryc.pl###sidebar-boxes `
~~`darmoweogoszenia-ryc.pl###sidebar-boxes`~~

również nie skutkują (niektóre z nich są sugerowane przez samego uBlocka Origin i z pomocą niego utworzone)

Żaden z wymienionych wyżej filtrów nie pokazuje się (dom na żółto) w dzienniku żądań uBlock Origin, a dokładniej generalnie problem wygląda tak, że wstawienie domeny przed filtr, powoduje, że filtr nie zaskakuje. Dopiero goły `###sidebar-boxes` działa. W ogóle to trochę dziwne, bo nie tylko filtry nie wyłapują domen, nawet curl nie wykrywa niektórych domen:
~~`curl: (6) Could not resolve host: www.darmoweogłoszenia.pl`~~
~~`curl: (6) Could not resolve host: darmoweogłoszenia.pl`~~
(natomiast te są wykrywane:  `xn--darmoweogoszenia-ryc.pl`  >> `www.xn--darmoweogoszenia-ryc.pl`)

~~A przecież w pasku przeglądarki jak wół widnieje ta niewykrywana domena.~~ Czy u innych też problem występuje? Ktoś rozwiąże tę zagadkę? Chyba ktoś się postarał, żeby ten baner przysporzył kłopotów, wystarczy spojrzeć na nazwę jednego z ciasteczek z tej strony: `zajebista_reklama_wyskakujaca`, chociaż nie wiem czy to chodzi akurat o ten baner, na stronie jest też kilka jebutnych skryptów inline.

**Comment by blocker999** [comment]
OK, przyjże się tej sprawie choć nieukrywam że jestem lajkiem więc prosze @F4z o pomoc.

**Comment by gomoku** [comment]
Zawsze sprawdzam na dwóch przeglądarkach: FF i Operze w najnowszych wersjach oficjalnych.

**Comment by blocker999** [comment]
OK, pytam bo opera i inne chromopodobne przeglądarki, lubią zaskakiwać no ale skoro taki sam problem jest na obu to raczej coś nietak z tą regułą, więc w dalszym ciągu czekamy na @F4z

**Comment by gomoku** [comment]
Hmm właśnie sprawdziłem dla pewności jeszcze raz na Operze i jednak ta reguła działa, ale na Firefoxie dalej nie działa.

**Comment by gomoku** [comment]
Zgłosiłem błąd odnośnie innego niedziałającego filtra na bug trackerze uBlocka, i okazało się, autor potwierdził błąd w uBlocku, błąd został szybko naprawiony, przy okazji przypadkiem okazało się, że także został naprawiony ten błąd, więc zamykam: https://github.com/gorhill/uBlock/issues/2938

**Comment by blocker999** [comment]
@hawkeye116477 Podobny przypadek co z socialami tylko na ublocku, wiec to jakiś bug.

**Comment by hawkeye116477** [comment]
@blocker999 Ta, wersja Adblocka z Chromium jest zabugowana, a ta z Firefoksa działa poprawnie.
