### ISSUE TITLE
planeteplus.pl

### ISSUE THREAD

**Issue by blocker999** [FiltersHeroes/PolishAnnoyanceFilters#80]
@hawkeye116477 Chodzi mi o tę zasłonę przed załadowaniem się strony czy usuwamy to czy przesadzam?

**Comment by hawkeye116477** [comment]
@blocker999 Nie wiem czy to w ogóle da się usunąć. To tak szybko się pojawia, że nawet nie zdążam kliknąć pickerem.

**Comment by hawkeye116477** [comment]
@blocker999 Nie wiem czy to w ogóle da się usunąć. To tak szybko się pojawia, że nawet nie zdążam kliknąć pickerem.

**Comment by blocker999** [comment]
@hawkeye116477 Da się da ale czy warto?

**Comment by hawkeye116477** [comment]
@blocker999 Chyba raczej nie warto, z kurtyną raczej to lepiej wygląda. A co o tym sądzi twój nowy kolega?

**Comment by blocker999** [comment]
Wole starego kolege @F4z zapytać o opinie

**Comment by F4z** [comment]
Ja bym zostawił.
