### ISSUE TITLE
auchandirect.pl

### ISSUE THREAD

**Issue by krystian3w** [FiltersHeroes/PolishAnnoyanceFilters#950]
### Moja konfiguracja
**Przeglądarka internetowa:** Firefox 60.0.1

**System operacyjny:** Android 7

**Bloker:** uBO 1.16.6

**Używane filtry:**
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Ciasteczkowe
4. Polskie Filtry Elementów Irytujących
5. Adguard’s Annoyance List
6. Fanboy’s Cookiemonster List

### Link bezpośredni (opcjonalny)

`https://www.auchandirect.pl/auchan-warszawa/pl/spozywcze/przetwory-owocowe-miod/kremy/kremy-czekoladowe-i-orzechowe/c-14165`

### Inne ważne informacje mogące mieć znaczenie (opcjonalne):

Pierwsze odwiedziny mają zablokowane przewijanie, jakoś dziwnie mają zrobiony pop-up z prośbą o kod pocztowy.

**Comment by hawkeye116477** [comment]
@krystian3w U mnie jest ok.

**Comment by krystian3w** [comment]
No u mnie też się odblokowało (wymusiłem aktualizacje wszystkich filtrów).
