### ISSUE TITLE
Bot

### ISSUE THREAD

**Issue by krystian3w** [FiltersHeroes/PolishAnnoyanceFilters#951]
Na wersji mobilnej pokazuje, że po każdej edycji dodaje tagi i np. przy kilku edycjach nagle ta sekcja ma połowę / całość mobilnego ekranu.

> ![image](https://user-images.githubusercontent.com/35370833/40358038-4a6510b2-5dbe-11e8-9be0-3c2c463f39ec.png) |
> --- |

**Comment by hawkeye116477** [comment]
No faktycznie tak jest, zobaczymy co da się zrobić, ale generalnie po każdej edycji musi przydzielać label, bo zawsze ktoś go może zmienić.
